// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/container-object-storage-interface/spec/cosi.proto

package cosi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProvisionerCreateBucketRequest_AnonymousBucketAccessMode int32

const (
	ProvisionerCreateBucketRequest_BUCKET_PRIVATE    ProvisionerCreateBucketRequest_AnonymousBucketAccessMode = 0
	ProvisionerCreateBucketRequest_BUCKET_READ_ONLY  ProvisionerCreateBucketRequest_AnonymousBucketAccessMode = 1
	ProvisionerCreateBucketRequest_BUCKET_WRITE_ONLY ProvisionerCreateBucketRequest_AnonymousBucketAccessMode = 2
	ProvisionerCreateBucketRequest_BUCKET_READ_WRITE ProvisionerCreateBucketRequest_AnonymousBucketAccessMode = 3
)

var ProvisionerCreateBucketRequest_AnonymousBucketAccessMode_name = map[int32]string{
	0: "BUCKET_PRIVATE",
	1: "BUCKET_READ_ONLY",
	2: "BUCKET_WRITE_ONLY",
	3: "BUCKET_READ_WRITE",
}

var ProvisionerCreateBucketRequest_AnonymousBucketAccessMode_value = map[string]int32{
	"BUCKET_PRIVATE":    0,
	"BUCKET_READ_ONLY":  1,
	"BUCKET_WRITE_ONLY": 2,
	"BUCKET_READ_WRITE": 3,
}

func (x ProvisionerCreateBucketRequest_AnonymousBucketAccessMode) String() string {
	return proto.EnumName(ProvisionerCreateBucketRequest_AnonymousBucketAccessMode_name, int32(x))
}

func (ProvisionerCreateBucketRequest_AnonymousBucketAccessMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{2, 0}
}

type ProvisionerGetInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvisionerGetInfoRequest) Reset()         { *m = ProvisionerGetInfoRequest{} }
func (m *ProvisionerGetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*ProvisionerGetInfoRequest) ProtoMessage()    {}
func (*ProvisionerGetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{0}
}

func (m *ProvisionerGetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionerGetInfoRequest.Unmarshal(m, b)
}
func (m *ProvisionerGetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionerGetInfoRequest.Marshal(b, m, deterministic)
}
func (m *ProvisionerGetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionerGetInfoRequest.Merge(m, src)
}
func (m *ProvisionerGetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_ProvisionerGetInfoRequest.Size(m)
}
func (m *ProvisionerGetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionerGetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionerGetInfoRequest proto.InternalMessageInfo

type ProvisionerGetInfoResponse struct {
	ProvisionerIdentity  string   `protobuf:"bytes,1,opt,name=provisioner_identity,json=provisionerIdentity,proto3" json:"provisioner_identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvisionerGetInfoResponse) Reset()         { *m = ProvisionerGetInfoResponse{} }
func (m *ProvisionerGetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*ProvisionerGetInfoResponse) ProtoMessage()    {}
func (*ProvisionerGetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{1}
}

func (m *ProvisionerGetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionerGetInfoResponse.Unmarshal(m, b)
}
func (m *ProvisionerGetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionerGetInfoResponse.Marshal(b, m, deterministic)
}
func (m *ProvisionerGetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionerGetInfoResponse.Merge(m, src)
}
func (m *ProvisionerGetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_ProvisionerGetInfoResponse.Size(m)
}
func (m *ProvisionerGetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionerGetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionerGetInfoResponse proto.InternalMessageInfo

func (m *ProvisionerGetInfoResponse) GetProvisionerIdentity() string {
	if m != nil {
		return m.ProvisionerIdentity
	}
	return ""
}

type ProvisionerCreateBucketRequest struct {
	BucketName                string                                                   `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	Region                    string                                                   `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Zone                      string                                                   `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	BucketContext             map[string]string                                        `protobuf:"bytes,4,rep,name=bucket_context,json=bucketContext,proto3" json:"bucket_context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	AnonymousBucketAccessMode ProvisionerCreateBucketRequest_AnonymousBucketAccessMode `protobuf:"varint,5,opt,name=anonymous_bucket_access_mode,json=anonymousBucketAccessMode,proto3,enum=cosi.v1alpha1.ProvisionerCreateBucketRequest_AnonymousBucketAccessMode" json:"anonymous_bucket_access_mode,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                                                 `json:"-"`
	XXX_unrecognized          []byte                                                   `json:"-"`
	XXX_sizecache             int32                                                    `json:"-"`
}

func (m *ProvisionerCreateBucketRequest) Reset()         { *m = ProvisionerCreateBucketRequest{} }
func (m *ProvisionerCreateBucketRequest) String() string { return proto.CompactTextString(m) }
func (*ProvisionerCreateBucketRequest) ProtoMessage()    {}
func (*ProvisionerCreateBucketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{2}
}

func (m *ProvisionerCreateBucketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionerCreateBucketRequest.Unmarshal(m, b)
}
func (m *ProvisionerCreateBucketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionerCreateBucketRequest.Marshal(b, m, deterministic)
}
func (m *ProvisionerCreateBucketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionerCreateBucketRequest.Merge(m, src)
}
func (m *ProvisionerCreateBucketRequest) XXX_Size() int {
	return xxx_messageInfo_ProvisionerCreateBucketRequest.Size(m)
}
func (m *ProvisionerCreateBucketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionerCreateBucketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionerCreateBucketRequest proto.InternalMessageInfo

func (m *ProvisionerCreateBucketRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *ProvisionerCreateBucketRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *ProvisionerCreateBucketRequest) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *ProvisionerCreateBucketRequest) GetBucketContext() map[string]string {
	if m != nil {
		return m.BucketContext
	}
	return nil
}

func (m *ProvisionerCreateBucketRequest) GetAnonymousBucketAccessMode() ProvisionerCreateBucketRequest_AnonymousBucketAccessMode {
	if m != nil {
		return m.AnonymousBucketAccessMode
	}
	return ProvisionerCreateBucketRequest_BUCKET_PRIVATE
}

type ProvisionerCreateBucketResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvisionerCreateBucketResponse) Reset()         { *m = ProvisionerCreateBucketResponse{} }
func (m *ProvisionerCreateBucketResponse) String() string { return proto.CompactTextString(m) }
func (*ProvisionerCreateBucketResponse) ProtoMessage()    {}
func (*ProvisionerCreateBucketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{3}
}

func (m *ProvisionerCreateBucketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionerCreateBucketResponse.Unmarshal(m, b)
}
func (m *ProvisionerCreateBucketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionerCreateBucketResponse.Marshal(b, m, deterministic)
}
func (m *ProvisionerCreateBucketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionerCreateBucketResponse.Merge(m, src)
}
func (m *ProvisionerCreateBucketResponse) XXX_Size() int {
	return xxx_messageInfo_ProvisionerCreateBucketResponse.Size(m)
}
func (m *ProvisionerCreateBucketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionerCreateBucketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionerCreateBucketResponse proto.InternalMessageInfo

type ProvisionerDeleteBucketRequest struct {
	BucketName           string            `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	Region               string            `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Zone                 string            `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	BucketContext        map[string]string `protobuf:"bytes,4,rep,name=bucket_context,json=bucketContext,proto3" json:"bucket_context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProvisionerDeleteBucketRequest) Reset()         { *m = ProvisionerDeleteBucketRequest{} }
func (m *ProvisionerDeleteBucketRequest) String() string { return proto.CompactTextString(m) }
func (*ProvisionerDeleteBucketRequest) ProtoMessage()    {}
func (*ProvisionerDeleteBucketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{4}
}

func (m *ProvisionerDeleteBucketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionerDeleteBucketRequest.Unmarshal(m, b)
}
func (m *ProvisionerDeleteBucketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionerDeleteBucketRequest.Marshal(b, m, deterministic)
}
func (m *ProvisionerDeleteBucketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionerDeleteBucketRequest.Merge(m, src)
}
func (m *ProvisionerDeleteBucketRequest) XXX_Size() int {
	return xxx_messageInfo_ProvisionerDeleteBucketRequest.Size(m)
}
func (m *ProvisionerDeleteBucketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionerDeleteBucketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionerDeleteBucketRequest proto.InternalMessageInfo

func (m *ProvisionerDeleteBucketRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *ProvisionerDeleteBucketRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *ProvisionerDeleteBucketRequest) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *ProvisionerDeleteBucketRequest) GetBucketContext() map[string]string {
	if m != nil {
		return m.BucketContext
	}
	return nil
}

type ProvisionerDeleteBucketResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvisionerDeleteBucketResponse) Reset()         { *m = ProvisionerDeleteBucketResponse{} }
func (m *ProvisionerDeleteBucketResponse) String() string { return proto.CompactTextString(m) }
func (*ProvisionerDeleteBucketResponse) ProtoMessage()    {}
func (*ProvisionerDeleteBucketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{5}
}

func (m *ProvisionerDeleteBucketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionerDeleteBucketResponse.Unmarshal(m, b)
}
func (m *ProvisionerDeleteBucketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionerDeleteBucketResponse.Marshal(b, m, deterministic)
}
func (m *ProvisionerDeleteBucketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionerDeleteBucketResponse.Merge(m, src)
}
func (m *ProvisionerDeleteBucketResponse) XXX_Size() int {
	return xxx_messageInfo_ProvisionerDeleteBucketResponse.Size(m)
}
func (m *ProvisionerDeleteBucketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionerDeleteBucketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionerDeleteBucketResponse proto.InternalMessageInfo

type ProvisionerGrantBucketAccessRequest struct {
	BucketName           string            `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	Region               string            `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Zone                 string            `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	BucketContext        map[string]string `protobuf:"bytes,4,rep,name=bucket_context,json=bucketContext,proto3" json:"bucket_context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Principal            string            `protobuf:"bytes,5,opt,name=principal,proto3" json:"principal,omitempty"`
	AccessPolicy         string            `protobuf:"bytes,6,opt,name=access_policy,json=accessPolicy,proto3" json:"access_policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProvisionerGrantBucketAccessRequest) Reset()         { *m = ProvisionerGrantBucketAccessRequest{} }
func (m *ProvisionerGrantBucketAccessRequest) String() string { return proto.CompactTextString(m) }
func (*ProvisionerGrantBucketAccessRequest) ProtoMessage()    {}
func (*ProvisionerGrantBucketAccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{6}
}

func (m *ProvisionerGrantBucketAccessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionerGrantBucketAccessRequest.Unmarshal(m, b)
}
func (m *ProvisionerGrantBucketAccessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionerGrantBucketAccessRequest.Marshal(b, m, deterministic)
}
func (m *ProvisionerGrantBucketAccessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionerGrantBucketAccessRequest.Merge(m, src)
}
func (m *ProvisionerGrantBucketAccessRequest) XXX_Size() int {
	return xxx_messageInfo_ProvisionerGrantBucketAccessRequest.Size(m)
}
func (m *ProvisionerGrantBucketAccessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionerGrantBucketAccessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionerGrantBucketAccessRequest proto.InternalMessageInfo

func (m *ProvisionerGrantBucketAccessRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *ProvisionerGrantBucketAccessRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *ProvisionerGrantBucketAccessRequest) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *ProvisionerGrantBucketAccessRequest) GetBucketContext() map[string]string {
	if m != nil {
		return m.BucketContext
	}
	return nil
}

func (m *ProvisionerGrantBucketAccessRequest) GetPrincipal() string {
	if m != nil {
		return m.Principal
	}
	return ""
}

func (m *ProvisionerGrantBucketAccessRequest) GetAccessPolicy() string {
	if m != nil {
		return m.AccessPolicy
	}
	return ""
}

type ProvisionerGrantBucketAccessResponse struct {
	// This is the account that is being provided access. This will
	// be required later to revoke access.
	Principal               string   `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	CredentialsFileContents string   `protobuf:"bytes,2,opt,name=credentials_file_contents,json=credentialsFileContents,proto3" json:"credentials_file_contents,omitempty"`
	CredentialsFilePath     string   `protobuf:"bytes,3,opt,name=credentials_file_path,json=credentialsFilePath,proto3" json:"credentials_file_path,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *ProvisionerGrantBucketAccessResponse) Reset()         { *m = ProvisionerGrantBucketAccessResponse{} }
func (m *ProvisionerGrantBucketAccessResponse) String() string { return proto.CompactTextString(m) }
func (*ProvisionerGrantBucketAccessResponse) ProtoMessage()    {}
func (*ProvisionerGrantBucketAccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{7}
}

func (m *ProvisionerGrantBucketAccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionerGrantBucketAccessResponse.Unmarshal(m, b)
}
func (m *ProvisionerGrantBucketAccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionerGrantBucketAccessResponse.Marshal(b, m, deterministic)
}
func (m *ProvisionerGrantBucketAccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionerGrantBucketAccessResponse.Merge(m, src)
}
func (m *ProvisionerGrantBucketAccessResponse) XXX_Size() int {
	return xxx_messageInfo_ProvisionerGrantBucketAccessResponse.Size(m)
}
func (m *ProvisionerGrantBucketAccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionerGrantBucketAccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionerGrantBucketAccessResponse proto.InternalMessageInfo

func (m *ProvisionerGrantBucketAccessResponse) GetPrincipal() string {
	if m != nil {
		return m.Principal
	}
	return ""
}

func (m *ProvisionerGrantBucketAccessResponse) GetCredentialsFileContents() string {
	if m != nil {
		return m.CredentialsFileContents
	}
	return ""
}

func (m *ProvisionerGrantBucketAccessResponse) GetCredentialsFilePath() string {
	if m != nil {
		return m.CredentialsFilePath
	}
	return ""
}

type ProvisionerRevokeBucketAccessRequest struct {
	BucketName           string            `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	Region               string            `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Zone                 string            `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	BucketContext        map[string]string `protobuf:"bytes,4,rep,name=bucket_context,json=bucketContext,proto3" json:"bucket_context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Principal            string            `protobuf:"bytes,5,opt,name=principal,proto3" json:"principal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProvisionerRevokeBucketAccessRequest) Reset()         { *m = ProvisionerRevokeBucketAccessRequest{} }
func (m *ProvisionerRevokeBucketAccessRequest) String() string { return proto.CompactTextString(m) }
func (*ProvisionerRevokeBucketAccessRequest) ProtoMessage()    {}
func (*ProvisionerRevokeBucketAccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{8}
}

func (m *ProvisionerRevokeBucketAccessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionerRevokeBucketAccessRequest.Unmarshal(m, b)
}
func (m *ProvisionerRevokeBucketAccessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionerRevokeBucketAccessRequest.Marshal(b, m, deterministic)
}
func (m *ProvisionerRevokeBucketAccessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionerRevokeBucketAccessRequest.Merge(m, src)
}
func (m *ProvisionerRevokeBucketAccessRequest) XXX_Size() int {
	return xxx_messageInfo_ProvisionerRevokeBucketAccessRequest.Size(m)
}
func (m *ProvisionerRevokeBucketAccessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionerRevokeBucketAccessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionerRevokeBucketAccessRequest proto.InternalMessageInfo

func (m *ProvisionerRevokeBucketAccessRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *ProvisionerRevokeBucketAccessRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *ProvisionerRevokeBucketAccessRequest) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *ProvisionerRevokeBucketAccessRequest) GetBucketContext() map[string]string {
	if m != nil {
		return m.BucketContext
	}
	return nil
}

func (m *ProvisionerRevokeBucketAccessRequest) GetPrincipal() string {
	if m != nil {
		return m.Principal
	}
	return ""
}

type ProvisionerRevokeBucketAccessResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvisionerRevokeBucketAccessResponse) Reset()         { *m = ProvisionerRevokeBucketAccessResponse{} }
func (m *ProvisionerRevokeBucketAccessResponse) String() string { return proto.CompactTextString(m) }
func (*ProvisionerRevokeBucketAccessResponse) ProtoMessage()    {}
func (*ProvisionerRevokeBucketAccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{9}
}

func (m *ProvisionerRevokeBucketAccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvisionerRevokeBucketAccessResponse.Unmarshal(m, b)
}
func (m *ProvisionerRevokeBucketAccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvisionerRevokeBucketAccessResponse.Marshal(b, m, deterministic)
}
func (m *ProvisionerRevokeBucketAccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionerRevokeBucketAccessResponse.Merge(m, src)
}
func (m *ProvisionerRevokeBucketAccessResponse) XXX_Size() int {
	return xxx_messageInfo_ProvisionerRevokeBucketAccessResponse.Size(m)
}
func (m *ProvisionerRevokeBucketAccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionerRevokeBucketAccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionerRevokeBucketAccessResponse proto.InternalMessageInfo

var E_AlphaEnum = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         1060,
	Name:          "cosi.v1alpha1.alpha_enum",
	Tag:           "varint,1060,opt,name=alpha_enum",
	Filename:      "github.com/container-object-storage-interface/spec/cosi.proto",
}

var E_AlphaEnumValue = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         1060,
	Name:          "cosi.v1alpha1.alpha_enum_value",
	Tag:           "varint,1060,opt,name=alpha_enum_value",
	Filename:      "github.com/container-object-storage-interface/spec/cosi.proto",
}

var E_CosiSecret = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         1059,
	Name:          "cosi.v1alpha1.cosi_secret",
	Tag:           "varint,1059,opt,name=cosi_secret",
	Filename:      "github.com/container-object-storage-interface/spec/cosi.proto",
}

var E_AlphaField = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         1060,
	Name:          "cosi.v1alpha1.alpha_field",
	Tag:           "varint,1060,opt,name=alpha_field",
	Filename:      "github.com/container-object-storage-interface/spec/cosi.proto",
}

var E_AlphaMessage = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         1060,
	Name:          "cosi.v1alpha1.alpha_message",
	Tag:           "varint,1060,opt,name=alpha_message",
	Filename:      "github.com/container-object-storage-interface/spec/cosi.proto",
}

var E_AlphaMethod = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         1060,
	Name:          "cosi.v1alpha1.alpha_method",
	Tag:           "varint,1060,opt,name=alpha_method",
	Filename:      "github.com/container-object-storage-interface/spec/cosi.proto",
}

var E_AlphaService = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         1060,
	Name:          "cosi.v1alpha1.alpha_service",
	Tag:           "varint,1060,opt,name=alpha_service",
	Filename:      "github.com/container-object-storage-interface/spec/cosi.proto",
}

func init() {
	proto.RegisterEnum("cosi.v1alpha1.ProvisionerCreateBucketRequest_AnonymousBucketAccessMode", ProvisionerCreateBucketRequest_AnonymousBucketAccessMode_name, ProvisionerCreateBucketRequest_AnonymousBucketAccessMode_value)
	proto.RegisterType((*ProvisionerGetInfoRequest)(nil), "cosi.v1alpha1.ProvisionerGetInfoRequest")
	proto.RegisterType((*ProvisionerGetInfoResponse)(nil), "cosi.v1alpha1.ProvisionerGetInfoResponse")
	proto.RegisterType((*ProvisionerCreateBucketRequest)(nil), "cosi.v1alpha1.ProvisionerCreateBucketRequest")
	proto.RegisterMapType((map[string]string)(nil), "cosi.v1alpha1.ProvisionerCreateBucketRequest.BucketContextEntry")
	proto.RegisterType((*ProvisionerCreateBucketResponse)(nil), "cosi.v1alpha1.ProvisionerCreateBucketResponse")
	proto.RegisterType((*ProvisionerDeleteBucketRequest)(nil), "cosi.v1alpha1.ProvisionerDeleteBucketRequest")
	proto.RegisterMapType((map[string]string)(nil), "cosi.v1alpha1.ProvisionerDeleteBucketRequest.BucketContextEntry")
	proto.RegisterType((*ProvisionerDeleteBucketResponse)(nil), "cosi.v1alpha1.ProvisionerDeleteBucketResponse")
	proto.RegisterType((*ProvisionerGrantBucketAccessRequest)(nil), "cosi.v1alpha1.ProvisionerGrantBucketAccessRequest")
	proto.RegisterMapType((map[string]string)(nil), "cosi.v1alpha1.ProvisionerGrantBucketAccessRequest.BucketContextEntry")
	proto.RegisterType((*ProvisionerGrantBucketAccessResponse)(nil), "cosi.v1alpha1.ProvisionerGrantBucketAccessResponse")
	proto.RegisterType((*ProvisionerRevokeBucketAccessRequest)(nil), "cosi.v1alpha1.ProvisionerRevokeBucketAccessRequest")
	proto.RegisterMapType((map[string]string)(nil), "cosi.v1alpha1.ProvisionerRevokeBucketAccessRequest.BucketContextEntry")
	proto.RegisterType((*ProvisionerRevokeBucketAccessResponse)(nil), "cosi.v1alpha1.ProvisionerRevokeBucketAccessResponse")
	proto.RegisterExtension(E_AlphaEnum)
	proto.RegisterExtension(E_AlphaEnumValue)
	proto.RegisterExtension(E_CosiSecret)
	proto.RegisterExtension(E_AlphaField)
	proto.RegisterExtension(E_AlphaMessage)
	proto.RegisterExtension(E_AlphaMethod)
	proto.RegisterExtension(E_AlphaService)
}

func init() {
	proto.RegisterFile("github.com/container-object-storage-interface/spec/cosi.proto", fileDescriptor_a281b1e87a2def48)
}

var fileDescriptor_a281b1e87a2def48 = []byte{
	// 907 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xce, 0x3a, 0x3f, 0x6a, 0x8e, 0x93, 0xc8, 0x4c, 0x53, 0xea, 0x98, 0xb4, 0x71, 0x5d, 0x10,
	0xe6, 0x22, 0xb6, 0xe2, 0x70, 0x81, 0x2c, 0x10, 0x4d, 0x52, 0xa7, 0x8a, 0x68, 0x9b, 0x68, 0x1b,
	0x8a, 0xe0, 0x66, 0x35, 0x5e, 0x1f, 0xdb, 0x43, 0xd6, 0x33, 0xcb, 0xce, 0xd8, 0x22, 0x7d, 0x01,
	0x7e, 0x9e, 0xa0, 0xf7, 0xf0, 0x08, 0x3c, 0x01, 0xef, 0xc2, 0x7b, 0xa0, 0x9d, 0x19, 0x93, 0xf5,
	0xcf, 0x3a, 0x31, 0xa4, 0x12, 0x77, 0xbb, 0xe7, 0x3b, 0xe7, 0x3b, 0xdf, 0x9e, 0x39, 0xe7, 0xcc,
	0xc2, 0x17, 0x1d, 0xa6, 0xba, 0xfd, 0x66, 0xc5, 0x17, 0xbd, 0xaa, 0x2f, 0xb8, 0xa2, 0x8c, 0x63,
	0xb4, 0x2b, 0x9a, 0xdf, 0xa3, 0xaf, 0x76, 0xa5, 0x12, 0x11, 0xed, 0xe0, 0x2e, 0xe3, 0x0a, 0xa3,
	0x36, 0xf5, 0xb1, 0x2a, 0x43, 0xf4, 0xab, 0xbe, 0x90, 0xac, 0x12, 0x46, 0x42, 0x09, 0xb2, 0xae,
	0x9f, 0x07, 0x7b, 0x34, 0x08, 0xbb, 0x74, 0xaf, 0x50, 0xec, 0x08, 0xd1, 0x09, 0xb0, 0xaa, 0xc1,
	0x66, 0xbf, 0x5d, 0x6d, 0xa1, 0xf4, 0x23, 0x16, 0x2a, 0x11, 0x99, 0x80, 0xd2, 0x07, 0xb0, 0x75,
	0x16, 0x89, 0x01, 0x93, 0x4c, 0x70, 0x8c, 0x9e, 0xa1, 0x3a, 0xe1, 0x6d, 0xe1, 0xe2, 0x0f, 0x7d,
	0x94, 0xaa, 0x74, 0x0a, 0x85, 0x69, 0xa0, 0x0c, 0x05, 0x97, 0x48, 0xf6, 0x60, 0x33, 0xbc, 0x42,
	0x3d, 0xd6, 0x42, 0xae, 0x98, 0xba, 0xcc, 0x3b, 0x45, 0xa7, 0xbc, 0xea, 0xde, 0x4d, 0x60, 0x27,
	0x16, 0x2a, 0xbd, 0x5d, 0x82, 0x87, 0x09, 0xc6, 0xa3, 0x08, 0xa9, 0xc2, 0xc3, 0xbe, 0x7f, 0x81,
	0xca, 0xe6, 0x24, 0x3b, 0x90, 0x6d, 0x6a, 0x83, 0xc7, 0x69, 0x0f, 0x2d, 0x19, 0x18, 0xd3, 0x4b,
	0xda, 0x43, 0xf2, 0x3e, 0xac, 0x44, 0xd8, 0x61, 0x82, 0xe7, 0x33, 0x1a, 0xb3, 0x6f, 0x84, 0xc0,
	0xd2, 0x1b, 0xc1, 0x31, 0xbf, 0xa8, 0xad, 0xfa, 0x99, 0x74, 0x60, 0xc3, 0x92, 0xc5, 0xb5, 0xc4,
	0x1f, 0x55, 0x7e, 0xa9, 0xb8, 0x58, 0xce, 0xd6, 0x9e, 0x54, 0x46, 0xea, 0x54, 0x99, 0xad, 0xa9,
	0x62, 0xde, 0x8e, 0x0c, 0x45, 0x83, 0xab, 0xe8, 0xd2, 0x5d, 0x6f, 0x26, 0x6d, 0xe4, 0x67, 0x07,
	0xb6, 0x29, 0x17, 0xfc, 0xb2, 0x27, 0xfa, 0xd2, 0xb3, 0x39, 0xa9, 0xef, 0xa3, 0x94, 0x5e, 0x4f,
	0xb4, 0x30, 0xbf, 0x5c, 0x74, 0xca, 0x1b, 0xb5, 0x67, 0xf3, 0xe5, 0x3d, 0x18, 0x32, 0x1a, 0xf3,
	0x81, 0xe6, 0x7b, 0x21, 0x5a, 0xe8, 0x6e, 0xd1, 0x34, 0xa8, 0xf0, 0x04, 0xc8, 0xa4, 0x5e, 0x92,
	0x83, 0xc5, 0x0b, 0x1c, 0x9e, 0x4d, 0xfc, 0x48, 0x36, 0x61, 0x79, 0x40, 0x83, 0x3e, 0xda, 0x32,
	0x9a, 0x97, 0x7a, 0xe6, 0x33, 0xa7, 0x24, 0x61, 0x2b, 0x35, 0x33, 0x21, 0xb0, 0x71, 0xf8, 0xf5,
	0xd1, 0x57, 0x8d, 0x73, 0xef, 0xcc, 0x3d, 0x79, 0x7d, 0x70, 0xde, 0xc8, 0x2d, 0x90, 0x4d, 0xc8,
	0x59, 0x9b, 0xdb, 0x38, 0x78, 0xea, 0x9d, 0xbe, 0x7c, 0xfe, 0x6d, 0xce, 0x21, 0xf7, 0xe0, 0x3d,
	0x6b, 0xfd, 0xc6, 0x3d, 0x39, 0x6f, 0x18, 0x73, 0x26, 0x61, 0xd6, 0xce, 0x1a, 0xcb, 0x2d, 0x96,
	0x1e, 0xc1, 0x4e, 0x6a, 0x35, 0x4c, 0xc3, 0x95, 0xde, 0x66, 0x46, 0xba, 0xe7, 0x29, 0x06, 0xf8,
	0x7f, 0xeb, 0x9e, 0x29, 0x9a, 0xae, 0xef, 0x9e, 0x5b, 0x38, 0xb2, 0xd1, 0xea, 0x8d, 0xaa, 0xb0,
	0xd5, 0xfb, 0x2b, 0x03, 0x8f, 0x93, 0xd3, 0x1c, 0x51, 0xae, 0x92, 0xa7, 0xfb, 0x4e, 0x4a, 0x18,
	0xa4, 0x94, 0xb0, 0x91, 0x5e, 0xc2, 0x34, 0x61, 0x37, 0x98, 0xc2, 0x6d, 0x58, 0x0d, 0x23, 0xc6,
	0x7d, 0x16, 0xd2, 0x40, 0x4f, 0xdc, 0xaa, 0x7b, 0x65, 0x20, 0x8f, 0x61, 0xdd, 0x4e, 0x64, 0x28,
	0x02, 0xe6, 0x5f, 0xe6, 0x57, 0xb4, 0xc7, 0x9a, 0x31, 0x9e, 0x69, 0xdb, 0x2d, 0x1c, 0xc5, 0x1f,
	0x0e, 0x7c, 0x38, 0xfb, 0x73, 0xec, 0xfe, 0x1c, 0x51, 0xeb, 0x8c, 0xab, 0xad, 0xc3, 0x96, 0x1f,
	0xa1, 0x5e, 0x9c, 0x34, 0x90, 0x5e, 0x9b, 0x05, 0x68, 0x6a, 0xc8, 0x95, 0xb4, 0x49, 0xef, 0x27,
	0x1c, 0x8e, 0x59, 0x80, 0x47, 0x16, 0x26, 0x35, 0xb8, 0x37, 0x11, 0x1b, 0x52, 0xd5, 0xb5, 0x47,
	0x73, 0x77, 0x2c, 0xee, 0x8c, 0xaa, 0x6e, 0xe9, 0xcf, 0xcc, 0x88, 0x6c, 0x17, 0x07, 0xe2, 0x02,
	0xdf, 0x79, 0x7f, 0xf4, 0x52, 0xfa, 0xe3, 0x38, 0xbd, 0x3f, 0x52, 0x95, 0xfd, 0xd7, 0x06, 0xb9,
	0x85, 0xb3, 0xff, 0x18, 0x3e, 0xba, 0x46, 0xa9, 0x39, 0xfb, 0xda, 0x2f, 0xcb, 0x90, 0x4d, 0x78,
	0x92, 0x0b, 0x20, 0x93, 0x37, 0x2d, 0x29, 0xcf, 0x98, 0x92, 0x91, 0x9b, 0xba, 0xf0, 0xc9, 0x0d,
	0x3c, 0xed, 0x1e, 0x58, 0x20, 0x6f, 0xe0, 0x7e, 0xca, 0xaa, 0x25, 0xbb, 0x73, 0x5d, 0x50, 0x85,
	0xca, 0x4d, 0xdd, 0x53, 0x72, 0x27, 0x17, 0xd5, 0xac, 0xdc, 0x53, 0xd6, 0xea, 0xac, 0xdc, 0x53,
	0xf7, 0xdf, 0x02, 0xf9, 0xc9, 0x81, 0xed, 0x59, 0x93, 0x49, 0x6a, 0xf3, 0x6f, 0xa5, 0xc2, 0xfe,
	0x5c, 0x31, 0x76, 0xf4, 0x7f, 0x75, 0xe0, 0xc1, 0xcc, 0x46, 0x21, 0xfb, 0xff, 0x62, 0x00, 0x0a,
	0x9f, 0xce, 0x17, 0x64, 0xc4, 0xd4, 0x3f, 0x07, 0xd0, 0xfe, 0x1e, 0xf2, 0x7e, 0x8f, 0x6c, 0x57,
	0xcc, 0x3f, 0x63, 0x65, 0xf8, 0xcf, 0x58, 0x69, 0xf0, 0x7e, 0xef, 0x34, 0x54, 0x4c, 0x70, 0x99,
	0xff, 0xfd, 0x4e, 0xd1, 0x29, 0xdf, 0x71, 0x57, 0x75, 0x40, 0x0c, 0xd4, 0x9f, 0x43, 0xee, 0x2a,
	0xda, 0xd3, 0xa3, 0x40, 0x1e, 0x4d, 0xe5, 0x78, 0x1d, 0x63, 0x63, 0x44, 0x1b, 0xff, 0x10, 0x69,
	0xb4, 0xfe, 0x25, 0x64, 0xe3, 0x4f, 0xf0, 0x24, 0xfa, 0x11, 0x2a, 0xf2, 0x60, 0x82, 0xe8, 0x98,
	0x61, 0xd0, 0x1a, 0x92, 0xfc, 0x66, 0x48, 0x20, 0x0e, 0x79, 0xa5, 0x23, 0x62, 0x02, 0x23, 0xa7,
	0x1d, 0x3b, 0x5e, 0x47, 0x60, 0x55, 0x98, 0xef, 0xd7, 0x48, 0xbd, 0x01, 0xeb, 0x86, 0xa0, 0x87,
	0x52, 0xd2, 0x0e, 0x92, 0x9d, 0x09, 0x8a, 0x17, 0x06, 0x19, 0x23, 0x59, 0xd3, 0x61, 0x16, 0xab,
	0x1f, 0xc2, 0xda, 0x90, 0x46, 0x75, 0x45, 0x8b, 0x3c, 0x9c, 0xc2, 0x12, 0x03, 0x63, 0x24, 0x59,
	0x4b, 0x12, 0x43, 0x57, 0x52, 0x24, 0x46, 0x03, 0xe6, 0x4f, 0x93, 0xf2, 0xca, 0x20, 0x53, 0xa5,
	0x58, 0xec, 0x70, 0xe5, 0xbb, 0xa5, 0xb8, 0x40, 0xcd, 0x15, 0x1d, 0xb5, 0xff, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x6a, 0x8d, 0xb5, 0xc4, 0x63, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProvisionerClient is the client API for Provisioner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProvisionerClient interface {
	ProvisionerGetInfo(ctx context.Context, in *ProvisionerGetInfoRequest, opts ...grpc.CallOption) (*ProvisionerGetInfoResponse, error)
	ProvisionerCreateBucket(ctx context.Context, in *ProvisionerCreateBucketRequest, opts ...grpc.CallOption) (*ProvisionerCreateBucketResponse, error)
	ProvisionerDeleteBucket(ctx context.Context, in *ProvisionerDeleteBucketRequest, opts ...grpc.CallOption) (*ProvisionerDeleteBucketResponse, error)
	ProvisionerGrantBucketAccess(ctx context.Context, in *ProvisionerGrantBucketAccessRequest, opts ...grpc.CallOption) (*ProvisionerGrantBucketAccessResponse, error)
	ProvisionerRevokeBucketAccess(ctx context.Context, in *ProvisionerRevokeBucketAccessRequest, opts ...grpc.CallOption) (*ProvisionerRevokeBucketAccessResponse, error)
}

type provisionerClient struct {
	cc *grpc.ClientConn
}

func NewProvisionerClient(cc *grpc.ClientConn) ProvisionerClient {
	return &provisionerClient{cc}
}

func (c *provisionerClient) ProvisionerGetInfo(ctx context.Context, in *ProvisionerGetInfoRequest, opts ...grpc.CallOption) (*ProvisionerGetInfoResponse, error) {
	out := new(ProvisionerGetInfoResponse)
	err := c.cc.Invoke(ctx, "/cosi.v1alpha1.Provisioner/ProvisionerGetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionerClient) ProvisionerCreateBucket(ctx context.Context, in *ProvisionerCreateBucketRequest, opts ...grpc.CallOption) (*ProvisionerCreateBucketResponse, error) {
	out := new(ProvisionerCreateBucketResponse)
	err := c.cc.Invoke(ctx, "/cosi.v1alpha1.Provisioner/ProvisionerCreateBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionerClient) ProvisionerDeleteBucket(ctx context.Context, in *ProvisionerDeleteBucketRequest, opts ...grpc.CallOption) (*ProvisionerDeleteBucketResponse, error) {
	out := new(ProvisionerDeleteBucketResponse)
	err := c.cc.Invoke(ctx, "/cosi.v1alpha1.Provisioner/ProvisionerDeleteBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionerClient) ProvisionerGrantBucketAccess(ctx context.Context, in *ProvisionerGrantBucketAccessRequest, opts ...grpc.CallOption) (*ProvisionerGrantBucketAccessResponse, error) {
	out := new(ProvisionerGrantBucketAccessResponse)
	err := c.cc.Invoke(ctx, "/cosi.v1alpha1.Provisioner/ProvisionerGrantBucketAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionerClient) ProvisionerRevokeBucketAccess(ctx context.Context, in *ProvisionerRevokeBucketAccessRequest, opts ...grpc.CallOption) (*ProvisionerRevokeBucketAccessResponse, error) {
	out := new(ProvisionerRevokeBucketAccessResponse)
	err := c.cc.Invoke(ctx, "/cosi.v1alpha1.Provisioner/ProvisionerRevokeBucketAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProvisionerServer is the server API for Provisioner service.
type ProvisionerServer interface {
	ProvisionerGetInfo(context.Context, *ProvisionerGetInfoRequest) (*ProvisionerGetInfoResponse, error)
	ProvisionerCreateBucket(context.Context, *ProvisionerCreateBucketRequest) (*ProvisionerCreateBucketResponse, error)
	ProvisionerDeleteBucket(context.Context, *ProvisionerDeleteBucketRequest) (*ProvisionerDeleteBucketResponse, error)
	ProvisionerGrantBucketAccess(context.Context, *ProvisionerGrantBucketAccessRequest) (*ProvisionerGrantBucketAccessResponse, error)
	ProvisionerRevokeBucketAccess(context.Context, *ProvisionerRevokeBucketAccessRequest) (*ProvisionerRevokeBucketAccessResponse, error)
}

// UnimplementedProvisionerServer can be embedded to have forward compatible implementations.
type UnimplementedProvisionerServer struct {
}

func (*UnimplementedProvisionerServer) ProvisionerGetInfo(ctx context.Context, req *ProvisionerGetInfoRequest) (*ProvisionerGetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionerGetInfo not implemented")
}
func (*UnimplementedProvisionerServer) ProvisionerCreateBucket(ctx context.Context, req *ProvisionerCreateBucketRequest) (*ProvisionerCreateBucketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionerCreateBucket not implemented")
}
func (*UnimplementedProvisionerServer) ProvisionerDeleteBucket(ctx context.Context, req *ProvisionerDeleteBucketRequest) (*ProvisionerDeleteBucketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionerDeleteBucket not implemented")
}
func (*UnimplementedProvisionerServer) ProvisionerGrantBucketAccess(ctx context.Context, req *ProvisionerGrantBucketAccessRequest) (*ProvisionerGrantBucketAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionerGrantBucketAccess not implemented")
}
func (*UnimplementedProvisionerServer) ProvisionerRevokeBucketAccess(ctx context.Context, req *ProvisionerRevokeBucketAccessRequest) (*ProvisionerRevokeBucketAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionerRevokeBucketAccess not implemented")
}

func RegisterProvisionerServer(s *grpc.Server, srv ProvisionerServer) {
	s.RegisterService(&_Provisioner_serviceDesc, srv)
}

func _Provisioner_ProvisionerGetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionerGetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionerServer).ProvisionerGetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosi.v1alpha1.Provisioner/ProvisionerGetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionerServer).ProvisionerGetInfo(ctx, req.(*ProvisionerGetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provisioner_ProvisionerCreateBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionerCreateBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionerServer).ProvisionerCreateBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosi.v1alpha1.Provisioner/ProvisionerCreateBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionerServer).ProvisionerCreateBucket(ctx, req.(*ProvisionerCreateBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provisioner_ProvisionerDeleteBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionerDeleteBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionerServer).ProvisionerDeleteBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosi.v1alpha1.Provisioner/ProvisionerDeleteBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionerServer).ProvisionerDeleteBucket(ctx, req.(*ProvisionerDeleteBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provisioner_ProvisionerGrantBucketAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionerGrantBucketAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionerServer).ProvisionerGrantBucketAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosi.v1alpha1.Provisioner/ProvisionerGrantBucketAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionerServer).ProvisionerGrantBucketAccess(ctx, req.(*ProvisionerGrantBucketAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provisioner_ProvisionerRevokeBucketAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionerRevokeBucketAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionerServer).ProvisionerRevokeBucketAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosi.v1alpha1.Provisioner/ProvisionerRevokeBucketAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionerServer).ProvisionerRevokeBucketAccess(ctx, req.(*ProvisionerRevokeBucketAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Provisioner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosi.v1alpha1.Provisioner",
	HandlerType: (*ProvisionerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProvisionerGetInfo",
			Handler:    _Provisioner_ProvisionerGetInfo_Handler,
		},
		{
			MethodName: "ProvisionerCreateBucket",
			Handler:    _Provisioner_ProvisionerCreateBucket_Handler,
		},
		{
			MethodName: "ProvisionerDeleteBucket",
			Handler:    _Provisioner_ProvisionerDeleteBucket_Handler,
		},
		{
			MethodName: "ProvisionerGrantBucketAccess",
			Handler:    _Provisioner_ProvisionerGrantBucketAccess_Handler,
		},
		{
			MethodName: "ProvisionerRevokeBucketAccess",
			Handler:    _Provisioner_ProvisionerRevokeBucketAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/container-object-storage-interface/spec/cosi.proto",
}
