// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/container-object-storage-interface/spec/cosi.proto

package cosi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// DataProtocol defines a set of constants used in Create and Grant requests.
type DataProtocol int32

const (
	DataProtocol_PROTOCOL_UNSPECIFIED DataProtocol = 0
	DataProtocol_AZURE_BLOB           DataProtocol = 1
	DataProtocol_GCS                  DataProtocol = 2
	DataProtocol_S3                   DataProtocol = 3
)

var DataProtocol_name = map[int32]string{
	0: "PROTOCOL_UNSPECIFIED",
	1: "AZURE_BLOB",
	2: "GCS",
	3: "S3",
}

var DataProtocol_value = map[string]int32{
	"PROTOCOL_UNSPECIFIED": 0,
	"AZURE_BLOB":           1,
	"GCS":                  2,
	"S3":                   3,
}

func (x DataProtocol) String() string {
	return proto.EnumName(DataProtocol_name, int32(x))
}

func (DataProtocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{0}
}

// AccessMode defines a common set of permissions among object stores
type AccessMode int32

const (
	AccessMode_MODE_UNSPECIFIED AccessMode = 0
	AccessMode_RO               AccessMode = 1
	AccessMode_WO               AccessMode = 2
	AccessMode_RW               AccessMode = 3
)

var AccessMode_name = map[int32]string{
	0: "MODE_UNSPECIFIED",
	1: "RO",
	2: "WO",
	3: "RW",
}

var AccessMode_value = map[string]int32{
	"MODE_UNSPECIFIED": 0,
	"RO":               1,
	"WO":               2,
	"RW":               3,
}

func (x AccessMode) String() string {
	return proto.EnumName(AccessMode_name, int32(x))
}

func (AccessMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{1}
}

// S3SignatureVersion defines the 2 supported versions of S3's authentication
type S3SignatureVersion int32

const (
	S3SignatureVersion_VERSION_UNSPECIFIED S3SignatureVersion = 0
	S3SignatureVersion_V2                  S3SignatureVersion = 1
	S3SignatureVersion_V4                  S3SignatureVersion = 2
)

var S3SignatureVersion_name = map[int32]string{
	0: "VERSION_UNSPECIFIED",
	1: "V2",
	2: "V4",
}

var S3SignatureVersion_value = map[string]int32{
	"VERSION_UNSPECIFIED": 0,
	"V2":                  1,
	"V4":                  2,
}

func (x S3SignatureVersion) String() string {
	return proto.EnumName(S3SignatureVersion_name, int32(x))
}

func (S3SignatureVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{2}
}

type DriverInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DriverInfoRequest) Reset()         { *m = DriverInfoRequest{} }
func (m *DriverInfoRequest) String() string { return proto.CompactTextString(m) }
func (*DriverInfoRequest) ProtoMessage()    {}
func (*DriverInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{0}
}

func (m *DriverInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DriverInfoRequest.Unmarshal(m, b)
}
func (m *DriverInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DriverInfoRequest.Marshal(b, m, deterministic)
}
func (m *DriverInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DriverInfoRequest.Merge(m, src)
}
func (m *DriverInfoRequest) XXX_Size() int {
	return xxx_messageInfo_DriverInfoRequest.Size(m)
}
func (m *DriverInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DriverInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DriverInfoRequest proto.InternalMessageInfo

type DriverInfoResponse struct {
	// DriverName
	DriverName string `protobuf:"bytes,1,opt,name=DriverName,proto3" json:"DriverName,omitempty"`
	// SupportedProtocols
	SupportedProtocols   []DataProtocol `protobuf:"varint,2,rep,packed,name=SupportedProtocols,proto3,enum=cosi.v1.DataProtocol" json:"SupportedProtocols,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DriverInfoResponse) Reset()         { *m = DriverInfoResponse{} }
func (m *DriverInfoResponse) String() string { return proto.CompactTextString(m) }
func (*DriverInfoResponse) ProtoMessage()    {}
func (*DriverInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{1}
}

func (m *DriverInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DriverInfoResponse.Unmarshal(m, b)
}
func (m *DriverInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DriverInfoResponse.Marshal(b, m, deterministic)
}
func (m *DriverInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DriverInfoResponse.Merge(m, src)
}
func (m *DriverInfoResponse) XXX_Size() int {
	return xxx_messageInfo_DriverInfoResponse.Size(m)
}
func (m *DriverInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DriverInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DriverInfoResponse proto.InternalMessageInfo

func (m *DriverInfoResponse) GetDriverName() string {
	if m != nil {
		return m.DriverName
	}
	return ""
}

func (m *DriverInfoResponse) GetSupportedProtocols() []DataProtocol {
	if m != nil {
		return m.SupportedProtocols
	}
	return nil
}

type S3Context struct {
	// returns the location where bucket will be created
	Location             string   `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S3Context) Reset()         { *m = S3Context{} }
func (m *S3Context) String() string { return proto.CompactTextString(m) }
func (*S3Context) ProtoMessage()    {}
func (*S3Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{2}
}

func (m *S3Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S3Context.Unmarshal(m, b)
}
func (m *S3Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S3Context.Marshal(b, m, deterministic)
}
func (m *S3Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S3Context.Merge(m, src)
}
func (m *S3Context) XXX_Size() int {
	return xxx_messageInfo_S3Context.Size(m)
}
func (m *S3Context) XXX_DiscardUnknown() {
	xxx_messageInfo_S3Context.DiscardUnknown(m)
}

var xxx_messageInfo_S3Context proto.InternalMessageInfo

func (m *S3Context) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type GCSContext struct {
	// returns the location where bucket is created
	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	// returns the project the bucket belongs to
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GCSContext) Reset()         { *m = GCSContext{} }
func (m *GCSContext) String() string { return proto.CompactTextString(m) }
func (*GCSContext) ProtoMessage()    {}
func (*GCSContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{3}
}

func (m *GCSContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GCSContext.Unmarshal(m, b)
}
func (m *GCSContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GCSContext.Marshal(b, m, deterministic)
}
func (m *GCSContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GCSContext.Merge(m, src)
}
func (m *GCSContext) XXX_Size() int {
	return xxx_messageInfo_GCSContext.Size(m)
}
func (m *GCSContext) XXX_DiscardUnknown() {
	xxx_messageInfo_GCSContext.DiscardUnknown(m)
}

var xxx_messageInfo_GCSContext proto.InternalMessageInfo

func (m *GCSContext) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *GCSContext) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type AzureContext struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AzureContext) Reset()         { *m = AzureContext{} }
func (m *AzureContext) String() string { return proto.CompactTextString(m) }
func (*AzureContext) ProtoMessage()    {}
func (*AzureContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{4}
}

func (m *AzureContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AzureContext.Unmarshal(m, b)
}
func (m *AzureContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AzureContext.Marshal(b, m, deterministic)
}
func (m *AzureContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AzureContext.Merge(m, src)
}
func (m *AzureContext) XXX_Size() int {
	return xxx_messageInfo_AzureContext.Size(m)
}
func (m *AzureContext) XXX_DiscardUnknown() {
	xxx_messageInfo_AzureContext.DiscardUnknown(m)
}

var xxx_messageInfo_AzureContext proto.InternalMessageInfo

type GenericContext struct {
	// generic output content
	BucketData           map[string]string `protobuf:"bytes,1,rep,name=bucket_data,json=bucketData,proto3" json:"bucket_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GenericContext) Reset()         { *m = GenericContext{} }
func (m *GenericContext) String() string { return proto.CompactTextString(m) }
func (*GenericContext) ProtoMessage()    {}
func (*GenericContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{5}
}

func (m *GenericContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericContext.Unmarshal(m, b)
}
func (m *GenericContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericContext.Marshal(b, m, deterministic)
}
func (m *GenericContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericContext.Merge(m, src)
}
func (m *GenericContext) XXX_Size() int {
	return xxx_messageInfo_GenericContext.Size(m)
}
func (m *GenericContext) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericContext.DiscardUnknown(m)
}

var xxx_messageInfo_GenericContext proto.InternalMessageInfo

func (m *GenericContext) GetBucketData() map[string]string {
	if m != nil {
		return m.BucketData
	}
	return nil
}

type ProviderContext struct {
	// Types that are valid to be assigned to ProviderContext:
	//	*ProviderContext_S3Context
	//	*ProviderContext_GcsContext
	//	*ProviderContext_AzureContext
	//	*ProviderContext_GenericContext
	ProviderContext      isProviderContext_ProviderContext `protobuf_oneof:"ProviderContext"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ProviderContext) Reset()         { *m = ProviderContext{} }
func (m *ProviderContext) String() string { return proto.CompactTextString(m) }
func (*ProviderContext) ProtoMessage()    {}
func (*ProviderContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{6}
}

func (m *ProviderContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderContext.Unmarshal(m, b)
}
func (m *ProviderContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderContext.Marshal(b, m, deterministic)
}
func (m *ProviderContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderContext.Merge(m, src)
}
func (m *ProviderContext) XXX_Size() int {
	return xxx_messageInfo_ProviderContext.Size(m)
}
func (m *ProviderContext) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderContext.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderContext proto.InternalMessageInfo

type isProviderContext_ProviderContext interface {
	isProviderContext_ProviderContext()
}

type ProviderContext_S3Context struct {
	S3Context *S3Context `protobuf:"bytes,1,opt,name=s3_context,json=s3Context,proto3,oneof"`
}

type ProviderContext_GcsContext struct {
	GcsContext *GCSContext `protobuf:"bytes,2,opt,name=gcs_context,json=gcsContext,proto3,oneof"`
}

type ProviderContext_AzureContext struct {
	AzureContext *AzureContext `protobuf:"bytes,3,opt,name=azure_context,json=azureContext,proto3,oneof"`
}

type ProviderContext_GenericContext struct {
	GenericContext *GenericContext `protobuf:"bytes,4,opt,name=generic_context,json=genericContext,proto3,oneof"`
}

func (*ProviderContext_S3Context) isProviderContext_ProviderContext() {}

func (*ProviderContext_GcsContext) isProviderContext_ProviderContext() {}

func (*ProviderContext_AzureContext) isProviderContext_ProviderContext() {}

func (*ProviderContext_GenericContext) isProviderContext_ProviderContext() {}

func (m *ProviderContext) GetProviderContext() isProviderContext_ProviderContext {
	if m != nil {
		return m.ProviderContext
	}
	return nil
}

func (m *ProviderContext) GetS3Context() *S3Context {
	if x, ok := m.GetProviderContext().(*ProviderContext_S3Context); ok {
		return x.S3Context
	}
	return nil
}

func (m *ProviderContext) GetGcsContext() *GCSContext {
	if x, ok := m.GetProviderContext().(*ProviderContext_GcsContext); ok {
		return x.GcsContext
	}
	return nil
}

func (m *ProviderContext) GetAzureContext() *AzureContext {
	if x, ok := m.GetProviderContext().(*ProviderContext_AzureContext); ok {
		return x.AzureContext
	}
	return nil
}

func (m *ProviderContext) GetGenericContext() *GenericContext {
	if x, ok := m.GetProviderContext().(*ProviderContext_GenericContext); ok {
		return x.GenericContext
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProviderContext) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProviderContext_S3Context)(nil),
		(*ProviderContext_GcsContext)(nil),
		(*ProviderContext_AzureContext)(nil),
		(*ProviderContext_GenericContext)(nil),
	}
}

type Bucket struct {
	// Name is the name of the bucket
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// provisioner used to create and other bucket operations
	// ProjectName this bucket created under
	ProviderContext *ProviderContext `protobuf:"bytes,2,opt,name=provider_context,json=providerContext,proto3" json:"provider_context,omitempty"`
	Provisioner     string           `protobuf:"bytes,3,opt,name=provisioner,proto3" json:"provisioner,omitempty"`
	// access mode
	AccessMode           AccessMode `protobuf:"varint,4,opt,name=access_mode,json=accessMode,proto3,enum=cosi.v1.AccessMode" json:"access_mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Bucket) Reset()         { *m = Bucket{} }
func (m *Bucket) String() string { return proto.CompactTextString(m) }
func (*Bucket) ProtoMessage()    {}
func (*Bucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{7}
}

func (m *Bucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucket.Unmarshal(m, b)
}
func (m *Bucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucket.Marshal(b, m, deterministic)
}
func (m *Bucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucket.Merge(m, src)
}
func (m *Bucket) XXX_Size() int {
	return xxx_messageInfo_Bucket.Size(m)
}
func (m *Bucket) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucket.DiscardUnknown(m)
}

var xxx_messageInfo_Bucket proto.InternalMessageInfo

func (m *Bucket) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Bucket) GetProviderContext() *ProviderContext {
	if m != nil {
		return m.ProviderContext
	}
	return nil
}

func (m *Bucket) GetProvisioner() string {
	if m != nil {
		return m.Provisioner
	}
	return ""
}

func (m *Bucket) GetAccessMode() AccessMode {
	if m != nil {
		return m.AccessMode
	}
	return AccessMode_MODE_UNSPECIFIED
}

type CreateBucketRequest struct {
	// bucket_name, This field is REQUIRED.
	// Maintain Idempotency.
	//    In the case of error, the CO MUST handle the gRPC error codes
	//    per the recovery behavior defined in the "CreateBucket Errors"
	//    section below.
	// BucketRequest:name
	BucketName string `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	// RequestProtocol, one of the predefined values
	// Driver must check the protocol used to match
	// BucketClass:supportedProtocols - {"azureblob", "gcs", "s3", ... } [3]
	// BucketRequest:protocol - use this as request protocol but check
	// if the protocol is in the BucketClass' suppportedProtocols
	RequestProtocol DataProtocol `protobuf:"varint,2,opt,name=request_protocol,json=requestProtocol,proto3,enum=cosi.v1.DataProtocol" json:"request_protocol,omitempty"`
	// DriverParameters, these are parameters that are extracted from
	// BuckerRequest and BucketClass so that the call has context.
	// For example GCS require projectName for CreateBucket to succeed.
	// BucketClass:provisioner - identify the
	// projectID if GCS
	ProviderContext  *ProviderContext  `protobuf:"bytes,3,opt,name=provider_context,json=providerContext,proto3" json:"provider_context,omitempty"`
	DriverParameters map[string]string `protobuf:"bytes,4,rep,name=driver_parameters,json=driverParameters,proto3" json:"driver_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// AccessMode is requested as RO, RW, WO and depends on driver.
	// If driver supports access mode if not ignores it
	// BucketClass:accessMode - {"ro", "wo", "rw"} [4]
	AccessMode AccessMode `protobuf:"varint,5,opt,name=access_mode,json=accessMode,proto3,enum=cosi.v1.AccessMode" json:"access_mode,omitempty"`
	// Information required to make createBucket call. This field is REQUIRED
	// A series of tokens, user name, etc based on protocol choice
	// BucketRequest:secretName will provide necessary security token to
	// connect to the provider API.
	// Azure:
	//    message AuthenticationData {
	//        option (cosi_secret) = true;
	//        string StorageAccountName = 1;
	//        string AccountKey = 2;
	//        string SasToken = 3;
	//    }
	// GCS:
	//    message AuthenticationData {
	//        option (cosi_secret) = true;
	//        string StorageAccountName = 1;
	//        string PrivateKeyName = 2;
	//        string PrivateKey = 3;
	//    }
	// S3:
	//    message AuthenticationData {
	//        option (cosi_secret) = true;
	//        string AccessKeyId = 1;
	//        string SecretKey = 2;
	//        string StsToken = 3;
	//        string UserName = 4;
	//    }
	Secrets              map[string]string `protobuf:"bytes,6,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateBucketRequest) Reset()         { *m = CreateBucketRequest{} }
func (m *CreateBucketRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBucketRequest) ProtoMessage()    {}
func (*CreateBucketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{8}
}

func (m *CreateBucketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBucketRequest.Unmarshal(m, b)
}
func (m *CreateBucketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBucketRequest.Marshal(b, m, deterministic)
}
func (m *CreateBucketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBucketRequest.Merge(m, src)
}
func (m *CreateBucketRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBucketRequest.Size(m)
}
func (m *CreateBucketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBucketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBucketRequest proto.InternalMessageInfo

func (m *CreateBucketRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *CreateBucketRequest) GetRequestProtocol() DataProtocol {
	if m != nil {
		return m.RequestProtocol
	}
	return DataProtocol_PROTOCOL_UNSPECIFIED
}

func (m *CreateBucketRequest) GetProviderContext() *ProviderContext {
	if m != nil {
		return m.ProviderContext
	}
	return nil
}

func (m *CreateBucketRequest) GetDriverParameters() map[string]string {
	if m != nil {
		return m.DriverParameters
	}
	return nil
}

func (m *CreateBucketRequest) GetAccessMode() AccessMode {
	if m != nil {
		return m.AccessMode
	}
	return AccessMode_MODE_UNSPECIFIED
}

func (m *CreateBucketRequest) GetSecrets() map[string]string {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type CreateBucketResponse struct {
	// Bucket returned
	Bucket               *Bucket  `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBucketResponse) Reset()         { *m = CreateBucketResponse{} }
func (m *CreateBucketResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBucketResponse) ProtoMessage()    {}
func (*CreateBucketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{9}
}

func (m *CreateBucketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBucketResponse.Unmarshal(m, b)
}
func (m *CreateBucketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBucketResponse.Marshal(b, m, deterministic)
}
func (m *CreateBucketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBucketResponse.Merge(m, src)
}
func (m *CreateBucketResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBucketResponse.Size(m)
}
func (m *CreateBucketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBucketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBucketResponse proto.InternalMessageInfo

func (m *CreateBucketResponse) GetBucket() *Bucket {
	if m != nil {
		return m.Bucket
	}
	return nil
}

type DeleteBucketRequest struct {
	// The name of the bucket to be deleted.
	// This field is REQUIRED.
	BucketName string `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	// RequestProtocol, one of the predefined values
	// Driver must check the protocol used to match
	// BucketClass:supportedProtocols - {"azureblob", "gcs", "s3", ... } [3]
	// BucketRequest:protocol - use this as request protocol but check
	// if the protocol is in the BucketClass' suppportedProtocols
	RequestProtocol DataProtocol `protobuf:"varint,2,opt,name=request_protocol,json=requestProtocol,proto3,enum=cosi.v1.DataProtocol" json:"request_protocol,omitempty"`
	// DriverParameters, these are parameters that are extracted from
	// BuckerRequest and BucketClass so that the call has context.
	// For example GCS require projectName for CreateBucket to succeed.
	// BucketClass:provisioner - identify the
	// projectID if GCS
	ProviderContext  *ProviderContext  `protobuf:"bytes,3,opt,name=provider_context,json=providerContext,proto3" json:"provider_context,omitempty"`
	DriverParameters map[string]string `protobuf:"bytes,4,rep,name=driver_parameters,json=driverParameters,proto3" json:"driver_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Secrets required by driver to complete bucket deletion request.
	// This field is OPTIONAL. Refer to the `Secrets Requirements`
	// section on how to use this field.
	// Azure:
	//    message AuthenticationData {
	//        option (cosi_secret) = true;
	//        string StorageAccountName = 1;
	//        string AccountKey = 2;
	//        string SasToken = 3;
	//    }
	// GCS:
	//    message AuthenticationData {
	//        option (cosi_secret) = true;
	//        string StorageAccountName = 1;
	//        string PrivateKeyName = 2;
	//        string PrivateKey = 3;
	//    }
	// S3:
	//    message AuthenticationData {
	//        option (cosi_secret) = true;
	//        string AccessKeyId = 1;
	//        string SecretKey = 2;
	//        string StsToken = 3;
	//        string UserName = 4;
	//    }
	Secrets              map[string]string `protobuf:"bytes,5,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeleteBucketRequest) Reset()         { *m = DeleteBucketRequest{} }
func (m *DeleteBucketRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBucketRequest) ProtoMessage()    {}
func (*DeleteBucketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{10}
}

func (m *DeleteBucketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBucketRequest.Unmarshal(m, b)
}
func (m *DeleteBucketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBucketRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBucketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBucketRequest.Merge(m, src)
}
func (m *DeleteBucketRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBucketRequest.Size(m)
}
func (m *DeleteBucketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBucketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBucketRequest proto.InternalMessageInfo

func (m *DeleteBucketRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *DeleteBucketRequest) GetRequestProtocol() DataProtocol {
	if m != nil {
		return m.RequestProtocol
	}
	return DataProtocol_PROTOCOL_UNSPECIFIED
}

func (m *DeleteBucketRequest) GetProviderContext() *ProviderContext {
	if m != nil {
		return m.ProviderContext
	}
	return nil
}

func (m *DeleteBucketRequest) GetDriverParameters() map[string]string {
	if m != nil {
		return m.DriverParameters
	}
	return nil
}

func (m *DeleteBucketRequest) GetSecrets() map[string]string {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type DeleteBucketResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBucketResponse) Reset()         { *m = DeleteBucketResponse{} }
func (m *DeleteBucketResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBucketResponse) ProtoMessage()    {}
func (*DeleteBucketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{11}
}

func (m *DeleteBucketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBucketResponse.Unmarshal(m, b)
}
func (m *DeleteBucketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBucketResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBucketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBucketResponse.Merge(m, src)
}
func (m *DeleteBucketResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBucketResponse.Size(m)
}
func (m *DeleteBucketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBucketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBucketResponse proto.InternalMessageInfo

type S3Credentials struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Permission           string   `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
	Owner                string   `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S3Credentials) Reset()         { *m = S3Credentials{} }
func (m *S3Credentials) String() string { return proto.CompactTextString(m) }
func (*S3Credentials) ProtoMessage()    {}
func (*S3Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{12}
}

func (m *S3Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S3Credentials.Unmarshal(m, b)
}
func (m *S3Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S3Credentials.Marshal(b, m, deterministic)
}
func (m *S3Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S3Credentials.Merge(m, src)
}
func (m *S3Credentials) XXX_Size() int {
	return xxx_messageInfo_S3Credentials.Size(m)
}
func (m *S3Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_S3Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_S3Credentials proto.InternalMessageInfo

func (m *S3Credentials) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *S3Credentials) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

func (m *S3Credentials) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type GCSCredentials struct {
	Entity               string   `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Domain               string   `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Project              string   `protobuf:"bytes,4,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GCSCredentials) Reset()         { *m = GCSCredentials{} }
func (m *GCSCredentials) String() string { return proto.CompactTextString(m) }
func (*GCSCredentials) ProtoMessage()    {}
func (*GCSCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{13}
}

func (m *GCSCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GCSCredentials.Unmarshal(m, b)
}
func (m *GCSCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GCSCredentials.Marshal(b, m, deterministic)
}
func (m *GCSCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GCSCredentials.Merge(m, src)
}
func (m *GCSCredentials) XXX_Size() int {
	return xxx_messageInfo_GCSCredentials.Size(m)
}
func (m *GCSCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_GCSCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_GCSCredentials proto.InternalMessageInfo

func (m *GCSCredentials) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

func (m *GCSCredentials) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *GCSCredentials) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *GCSCredentials) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type AzureCredentials struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Permission           string   `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AzureCredentials) Reset()         { *m = AzureCredentials{} }
func (m *AzureCredentials) String() string { return proto.CompactTextString(m) }
func (*AzureCredentials) ProtoMessage()    {}
func (*AzureCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{14}
}

func (m *AzureCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AzureCredentials.Unmarshal(m, b)
}
func (m *AzureCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AzureCredentials.Marshal(b, m, deterministic)
}
func (m *AzureCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AzureCredentials.Merge(m, src)
}
func (m *AzureCredentials) XXX_Size() int {
	return xxx_messageInfo_AzureCredentials.Size(m)
}
func (m *AzureCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_AzureCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_AzureCredentials proto.InternalMessageInfo

func (m *AzureCredentials) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AzureCredentials) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

type GenericCredentials struct {
	// generic output content
	Credentials          map[string]string `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GenericCredentials) Reset()         { *m = GenericCredentials{} }
func (m *GenericCredentials) String() string { return proto.CompactTextString(m) }
func (*GenericCredentials) ProtoMessage()    {}
func (*GenericCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{15}
}

func (m *GenericCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericCredentials.Unmarshal(m, b)
}
func (m *GenericCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericCredentials.Marshal(b, m, deterministic)
}
func (m *GenericCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericCredentials.Merge(m, src)
}
func (m *GenericCredentials) XXX_Size() int {
	return xxx_messageInfo_GenericCredentials.Size(m)
}
func (m *GenericCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_GenericCredentials proto.InternalMessageInfo

func (m *GenericCredentials) GetCredentials() map[string]string {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type ProviderCredentials struct {
	// Types that are valid to be assigned to ProviderCredentials:
	//	*ProviderCredentials_S3Credentials
	//	*ProviderCredentials_GcsCredentials
	//	*ProviderCredentials_AzureCredentials
	//	*ProviderCredentials_GenericCredentials
	ProviderCredentials  isProviderCredentials_ProviderCredentials `protobuf_oneof:"ProviderCredentials"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *ProviderCredentials) Reset()         { *m = ProviderCredentials{} }
func (m *ProviderCredentials) String() string { return proto.CompactTextString(m) }
func (*ProviderCredentials) ProtoMessage()    {}
func (*ProviderCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{16}
}

func (m *ProviderCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderCredentials.Unmarshal(m, b)
}
func (m *ProviderCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderCredentials.Marshal(b, m, deterministic)
}
func (m *ProviderCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderCredentials.Merge(m, src)
}
func (m *ProviderCredentials) XXX_Size() int {
	return xxx_messageInfo_ProviderCredentials.Size(m)
}
func (m *ProviderCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderCredentials proto.InternalMessageInfo

type isProviderCredentials_ProviderCredentials interface {
	isProviderCredentials_ProviderCredentials()
}

type ProviderCredentials_S3Credentials struct {
	S3Credentials *S3Credentials `protobuf:"bytes,1,opt,name=s3_credentials,json=s3Credentials,proto3,oneof"`
}

type ProviderCredentials_GcsCredentials struct {
	GcsCredentials *GCSCredentials `protobuf:"bytes,2,opt,name=gcs_credentials,json=gcsCredentials,proto3,oneof"`
}

type ProviderCredentials_AzureCredentials struct {
	AzureCredentials *AzureCredentials `protobuf:"bytes,3,opt,name=azure_credentials,json=azureCredentials,proto3,oneof"`
}

type ProviderCredentials_GenericCredentials struct {
	GenericCredentials *GenericCredentials `protobuf:"bytes,4,opt,name=generic_credentials,json=genericCredentials,proto3,oneof"`
}

func (*ProviderCredentials_S3Credentials) isProviderCredentials_ProviderCredentials() {}

func (*ProviderCredentials_GcsCredentials) isProviderCredentials_ProviderCredentials() {}

func (*ProviderCredentials_AzureCredentials) isProviderCredentials_ProviderCredentials() {}

func (*ProviderCredentials_GenericCredentials) isProviderCredentials_ProviderCredentials() {}

func (m *ProviderCredentials) GetProviderCredentials() isProviderCredentials_ProviderCredentials {
	if m != nil {
		return m.ProviderCredentials
	}
	return nil
}

func (m *ProviderCredentials) GetS3Credentials() *S3Credentials {
	if x, ok := m.GetProviderCredentials().(*ProviderCredentials_S3Credentials); ok {
		return x.S3Credentials
	}
	return nil
}

func (m *ProviderCredentials) GetGcsCredentials() *GCSCredentials {
	if x, ok := m.GetProviderCredentials().(*ProviderCredentials_GcsCredentials); ok {
		return x.GcsCredentials
	}
	return nil
}

func (m *ProviderCredentials) GetAzureCredentials() *AzureCredentials {
	if x, ok := m.GetProviderCredentials().(*ProviderCredentials_AzureCredentials); ok {
		return x.AzureCredentials
	}
	return nil
}

func (m *ProviderCredentials) GetGenericCredentials() *GenericCredentials {
	if x, ok := m.GetProviderCredentials().(*ProviderCredentials_GenericCredentials); ok {
		return x.GenericCredentials
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProviderCredentials) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProviderCredentials_S3Credentials)(nil),
		(*ProviderCredentials_GcsCredentials)(nil),
		(*ProviderCredentials_AzureCredentials)(nil),
		(*ProviderCredentials_GenericCredentials)(nil),
	}
}

type GrantBucketAccessRequest struct {
	// The name of the bucket to be granted access.
	// This field is REQUIRED.
	BucketName string `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	// RequestProtocol, one of the predefined values
	// Driver must check the protocol used to match
	// BucketClass:supportedProtocols - {"azureblob", "gcs", "s3", ... } [3]
	// BucketRequest:protocol - use this as request protocol but check
	// if the protocol is in the BucketClass' suppportedProtocols
	RequestProtocol DataProtocol `protobuf:"varint,2,opt,name=request_protocol,json=requestProtocol,proto3,enum=cosi.v1.DataProtocol" json:"request_protocol,omitempty"`
	// permission granted
	Permissions map[string]string `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// provisioner used to create and other bucket operations
	// ProjectName this bucket created under
	ProviderContext      *ProviderContext  `protobuf:"bytes,4,opt,name=provider_context,json=providerContext,proto3" json:"provider_context,omitempty"`
	Secrets              map[string]string `protobuf:"bytes,5,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GrantBucketAccessRequest) Reset()         { *m = GrantBucketAccessRequest{} }
func (m *GrantBucketAccessRequest) String() string { return proto.CompactTextString(m) }
func (*GrantBucketAccessRequest) ProtoMessage()    {}
func (*GrantBucketAccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{17}
}

func (m *GrantBucketAccessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrantBucketAccessRequest.Unmarshal(m, b)
}
func (m *GrantBucketAccessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrantBucketAccessRequest.Marshal(b, m, deterministic)
}
func (m *GrantBucketAccessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantBucketAccessRequest.Merge(m, src)
}
func (m *GrantBucketAccessRequest) XXX_Size() int {
	return xxx_messageInfo_GrantBucketAccessRequest.Size(m)
}
func (m *GrantBucketAccessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantBucketAccessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GrantBucketAccessRequest proto.InternalMessageInfo

func (m *GrantBucketAccessRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *GrantBucketAccessRequest) GetRequestProtocol() DataProtocol {
	if m != nil {
		return m.RequestProtocol
	}
	return DataProtocol_PROTOCOL_UNSPECIFIED
}

func (m *GrantBucketAccessRequest) GetPermissions() map[string]string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *GrantBucketAccessRequest) GetProviderContext() *ProviderContext {
	if m != nil {
		return m.ProviderContext
	}
	return nil
}

func (m *GrantBucketAccessRequest) GetSecrets() map[string]string {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type GrantBucketAccessResponse struct {
	// No data returned by this call other than error or success code
	Creds                []*ProviderCredentials `protobuf:"bytes,1,rep,name=creds,proto3" json:"creds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GrantBucketAccessResponse) Reset()         { *m = GrantBucketAccessResponse{} }
func (m *GrantBucketAccessResponse) String() string { return proto.CompactTextString(m) }
func (*GrantBucketAccessResponse) ProtoMessage()    {}
func (*GrantBucketAccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{18}
}

func (m *GrantBucketAccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrantBucketAccessResponse.Unmarshal(m, b)
}
func (m *GrantBucketAccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrantBucketAccessResponse.Marshal(b, m, deterministic)
}
func (m *GrantBucketAccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantBucketAccessResponse.Merge(m, src)
}
func (m *GrantBucketAccessResponse) XXX_Size() int {
	return xxx_messageInfo_GrantBucketAccessResponse.Size(m)
}
func (m *GrantBucketAccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantBucketAccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GrantBucketAccessResponse proto.InternalMessageInfo

func (m *GrantBucketAccessResponse) GetCreds() []*ProviderCredentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

type RevokeBucketAccessRequest struct {
	// The name of the bucket to be granted access.
	// This field is REQUIRED.
	BucketName string `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	// RequestProtocol, one of the predefined values
	// Driver must check the protocol used to match
	// BucketClass:supportedProtocols - {"azureblob", "gcs", "s3", ... } [3]
	// BucketRequest:protocol - use this as request protocol but check
	// if the protocol is in the BucketClass' suppportedProtocols
	RequestProtocol DataProtocol `protobuf:"varint,2,opt,name=request_protocol,json=requestProtocol,proto3,enum=cosi.v1.DataProtocol" json:"request_protocol,omitempty"`
	// the service_account from which permissions are revoked
	ServiceAccount *ProviderCredentials `protobuf:"bytes,3,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	// permission revoked
	Permissions map[string]string `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// provisioner used to create and other bucket operations
	// ProjectName this bucket created under
	ProviderContext      *ProviderContext  `protobuf:"bytes,5,opt,name=provider_context,json=providerContext,proto3" json:"provider_context,omitempty"`
	Secrets              map[string]string `protobuf:"bytes,6,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RevokeBucketAccessRequest) Reset()         { *m = RevokeBucketAccessRequest{} }
func (m *RevokeBucketAccessRequest) String() string { return proto.CompactTextString(m) }
func (*RevokeBucketAccessRequest) ProtoMessage()    {}
func (*RevokeBucketAccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{19}
}

func (m *RevokeBucketAccessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeBucketAccessRequest.Unmarshal(m, b)
}
func (m *RevokeBucketAccessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeBucketAccessRequest.Marshal(b, m, deterministic)
}
func (m *RevokeBucketAccessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeBucketAccessRequest.Merge(m, src)
}
func (m *RevokeBucketAccessRequest) XXX_Size() int {
	return xxx_messageInfo_RevokeBucketAccessRequest.Size(m)
}
func (m *RevokeBucketAccessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeBucketAccessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeBucketAccessRequest proto.InternalMessageInfo

func (m *RevokeBucketAccessRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *RevokeBucketAccessRequest) GetRequestProtocol() DataProtocol {
	if m != nil {
		return m.RequestProtocol
	}
	return DataProtocol_PROTOCOL_UNSPECIFIED
}

func (m *RevokeBucketAccessRequest) GetServiceAccount() *ProviderCredentials {
	if m != nil {
		return m.ServiceAccount
	}
	return nil
}

func (m *RevokeBucketAccessRequest) GetPermissions() map[string]string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *RevokeBucketAccessRequest) GetProviderContext() *ProviderContext {
	if m != nil {
		return m.ProviderContext
	}
	return nil
}

func (m *RevokeBucketAccessRequest) GetSecrets() map[string]string {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type RevokeBucketAccessResponse struct {
	// No data returned by this call other than error or success code
	Creds                []*ProviderCredentials `protobuf:"bytes,1,rep,name=creds,proto3" json:"creds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RevokeBucketAccessResponse) Reset()         { *m = RevokeBucketAccessResponse{} }
func (m *RevokeBucketAccessResponse) String() string { return proto.CompactTextString(m) }
func (*RevokeBucketAccessResponse) ProtoMessage()    {}
func (*RevokeBucketAccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a281b1e87a2def48, []int{20}
}

func (m *RevokeBucketAccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeBucketAccessResponse.Unmarshal(m, b)
}
func (m *RevokeBucketAccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeBucketAccessResponse.Marshal(b, m, deterministic)
}
func (m *RevokeBucketAccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeBucketAccessResponse.Merge(m, src)
}
func (m *RevokeBucketAccessResponse) XXX_Size() int {
	return xxx_messageInfo_RevokeBucketAccessResponse.Size(m)
}
func (m *RevokeBucketAccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeBucketAccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeBucketAccessResponse proto.InternalMessageInfo

func (m *RevokeBucketAccessResponse) GetCreds() []*ProviderCredentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

var E_AlphaEnum = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         1060,
	Name:          "cosi.v1.alpha_enum",
	Tag:           "varint,1060,opt,name=alpha_enum",
	Filename:      "github.com/container-object-storage-interface/spec/cosi.proto",
}

var E_AlphaEnumValue = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         1060,
	Name:          "cosi.v1.alpha_enum_value",
	Tag:           "varint,1060,opt,name=alpha_enum_value",
	Filename:      "github.com/container-object-storage-interface/spec/cosi.proto",
}

var E_CosiSecret = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         1059,
	Name:          "cosi.v1.cosi_secret",
	Tag:           "varint,1059,opt,name=cosi_secret",
	Filename:      "github.com/container-object-storage-interface/spec/cosi.proto",
}

var E_AlphaField = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         1060,
	Name:          "cosi.v1.alpha_field",
	Tag:           "varint,1060,opt,name=alpha_field",
	Filename:      "github.com/container-object-storage-interface/spec/cosi.proto",
}

var E_AlphaMessage = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         1060,
	Name:          "cosi.v1.alpha_message",
	Tag:           "varint,1060,opt,name=alpha_message",
	Filename:      "github.com/container-object-storage-interface/spec/cosi.proto",
}

var E_AlphaMethod = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         1060,
	Name:          "cosi.v1.alpha_method",
	Tag:           "varint,1060,opt,name=alpha_method",
	Filename:      "github.com/container-object-storage-interface/spec/cosi.proto",
}

var E_AlphaService = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         1060,
	Name:          "cosi.v1.alpha_service",
	Tag:           "varint,1060,opt,name=alpha_service",
	Filename:      "github.com/container-object-storage-interface/spec/cosi.proto",
}

func init() {
	proto.RegisterEnum("cosi.v1.DataProtocol", DataProtocol_name, DataProtocol_value)
	proto.RegisterEnum("cosi.v1.AccessMode", AccessMode_name, AccessMode_value)
	proto.RegisterEnum("cosi.v1.S3SignatureVersion", S3SignatureVersion_name, S3SignatureVersion_value)
	proto.RegisterType((*DriverInfoRequest)(nil), "cosi.v1.DriverInfoRequest")
	proto.RegisterType((*DriverInfoResponse)(nil), "cosi.v1.DriverInfoResponse")
	proto.RegisterType((*S3Context)(nil), "cosi.v1.S3Context")
	proto.RegisterType((*GCSContext)(nil), "cosi.v1.GCSContext")
	proto.RegisterType((*AzureContext)(nil), "cosi.v1.AzureContext")
	proto.RegisterType((*GenericContext)(nil), "cosi.v1.GenericContext")
	proto.RegisterMapType((map[string]string)(nil), "cosi.v1.GenericContext.BucketDataEntry")
	proto.RegisterType((*ProviderContext)(nil), "cosi.v1.ProviderContext")
	proto.RegisterType((*Bucket)(nil), "cosi.v1.Bucket")
	proto.RegisterType((*CreateBucketRequest)(nil), "cosi.v1.CreateBucketRequest")
	proto.RegisterMapType((map[string]string)(nil), "cosi.v1.CreateBucketRequest.DriverParametersEntry")
	proto.RegisterMapType((map[string]string)(nil), "cosi.v1.CreateBucketRequest.SecretsEntry")
	proto.RegisterType((*CreateBucketResponse)(nil), "cosi.v1.CreateBucketResponse")
	proto.RegisterType((*DeleteBucketRequest)(nil), "cosi.v1.DeleteBucketRequest")
	proto.RegisterMapType((map[string]string)(nil), "cosi.v1.DeleteBucketRequest.DriverParametersEntry")
	proto.RegisterMapType((map[string]string)(nil), "cosi.v1.DeleteBucketRequest.SecretsEntry")
	proto.RegisterType((*DeleteBucketResponse)(nil), "cosi.v1.DeleteBucketResponse")
	proto.RegisterType((*S3Credentials)(nil), "cosi.v1.S3Credentials")
	proto.RegisterType((*GCSCredentials)(nil), "cosi.v1.GCSCredentials")
	proto.RegisterType((*AzureCredentials)(nil), "cosi.v1.AzureCredentials")
	proto.RegisterType((*GenericCredentials)(nil), "cosi.v1.GenericCredentials")
	proto.RegisterMapType((map[string]string)(nil), "cosi.v1.GenericCredentials.CredentialsEntry")
	proto.RegisterType((*ProviderCredentials)(nil), "cosi.v1.ProviderCredentials")
	proto.RegisterType((*GrantBucketAccessRequest)(nil), "cosi.v1.GrantBucketAccessRequest")
	proto.RegisterMapType((map[string]string)(nil), "cosi.v1.GrantBucketAccessRequest.PermissionsEntry")
	proto.RegisterMapType((map[string]string)(nil), "cosi.v1.GrantBucketAccessRequest.SecretsEntry")
	proto.RegisterType((*GrantBucketAccessResponse)(nil), "cosi.v1.GrantBucketAccessResponse")
	proto.RegisterType((*RevokeBucketAccessRequest)(nil), "cosi.v1.RevokeBucketAccessRequest")
	proto.RegisterMapType((map[string]string)(nil), "cosi.v1.RevokeBucketAccessRequest.PermissionsEntry")
	proto.RegisterMapType((map[string]string)(nil), "cosi.v1.RevokeBucketAccessRequest.SecretsEntry")
	proto.RegisterType((*RevokeBucketAccessResponse)(nil), "cosi.v1.RevokeBucketAccessResponse")
	proto.RegisterExtension(E_AlphaEnum)
	proto.RegisterExtension(E_AlphaEnumValue)
	proto.RegisterExtension(E_CosiSecret)
	proto.RegisterExtension(E_AlphaField)
	proto.RegisterExtension(E_AlphaMessage)
	proto.RegisterExtension(E_AlphaMethod)
	proto.RegisterExtension(E_AlphaService)
}

func init() {
	proto.RegisterFile("github.com/container-object-storage-interface/spec/cosi.proto", fileDescriptor_a281b1e87a2def48)
}

var fileDescriptor_a281b1e87a2def48 = []byte{
	// 1484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x58, 0xcb, 0x6e, 0xdb, 0x46,
	0x17, 0xd6, 0xcd, 0x72, 0x7c, 0x64, 0xcb, 0xf4, 0xd8, 0x49, 0x14, 0xfd, 0xb9, 0x38, 0xfc, 0x17,
	0x71, 0x83, 0x46, 0x46, 0xad, 0xa0, 0x28, 0x84, 0x5c, 0x6a, 0xc9, 0x8a, 0x65, 0x20, 0xb6, 0x0c,
	0x2a, 0x76, 0x80, 0x00, 0x85, 0x30, 0xa6, 0xc6, 0x0a, 0x1b, 0x89, 0xc3, 0xce, 0x50, 0x4e, 0xd3,
	0x3e, 0x46, 0x57, 0xed, 0xb6, 0x59, 0xf4, 0x15, 0xfa, 0x0c, 0x7d, 0x87, 0xae, 0xba, 0xe9, 0x5b,
	0x14, 0x73, 0x21, 0x45, 0x51, 0xf4, 0x2d, 0x8b, 0x34, 0xe8, 0xca, 0x33, 0x73, 0xce, 0xf9, 0xf4,
	0x9d, 0xc3, 0x73, 0x83, 0xe1, 0x71, 0xdf, 0xf1, 0x5f, 0x8f, 0x8e, 0x2a, 0x36, 0x1d, 0xae, 0xdb,
	0xd4, 0xf5, 0xb1, 0xe3, 0x12, 0xf6, 0x80, 0x1e, 0x7d, 0x4b, 0x6c, 0xff, 0x01, 0xf7, 0x29, 0xc3,
	0x7d, 0xf2, 0xc0, 0x71, 0x7d, 0xc2, 0x8e, 0xb1, 0x4d, 0xd6, 0xb9, 0x47, 0xec, 0x75, 0x9b, 0x72,
	0xa7, 0xe2, 0x31, 0xea, 0x53, 0x34, 0x2b, 0xcf, 0x27, 0x5f, 0x94, 0x57, 0xfb, 0x94, 0xf6, 0x07,
	0x64, 0x5d, 0x3e, 0x1f, 0x8d, 0x8e, 0xd7, 0x7b, 0x84, 0xdb, 0xcc, 0xf1, 0x7c, 0xca, 0x94, 0x6a,
	0xf9, 0x4e, 0x5c, 0xc3, 0x77, 0x86, 0x84, 0xfb, 0x78, 0xe8, 0x69, 0x85, 0xdb, 0x71, 0x85, 0xb7,
	0x0c, 0x7b, 0x1e, 0x61, 0x5c, 0xc9, 0xcd, 0x65, 0x58, 0xda, 0x62, 0xce, 0x09, 0x61, 0x3b, 0xee,
	0x31, 0xb5, 0xc8, 0x77, 0x23, 0xc2, 0x7d, 0xf3, 0x47, 0x40, 0xd1, 0x47, 0xee, 0x51, 0x97, 0x13,
	0x74, 0x1b, 0x40, 0xbd, 0xee, 0xe1, 0x21, 0x29, 0xa5, 0x57, 0xd3, 0x6b, 0x73, 0x56, 0xe4, 0x05,
	0x35, 0x01, 0x75, 0x46, 0x9e, 0x47, 0x99, 0x4f, 0x7a, 0xfb, 0x02, 0xdc, 0xa6, 0x03, 0x5e, 0xca,
	0xac, 0x66, 0xd7, 0x8a, 0x1b, 0x57, 0x2b, 0xda, 0xa7, 0xca, 0x16, 0xf6, 0x71, 0x20, 0xb5, 0x12,
	0x0c, 0xcc, 0x7b, 0x30, 0xd7, 0xa9, 0x36, 0xa8, 0xeb, 0x93, 0xef, 0x7d, 0x54, 0x86, 0x2b, 0x03,
	0x6a, 0x63, 0xdf, 0xa1, 0xae, 0xfe, 0xc5, 0xf0, 0x6e, 0xd6, 0x01, 0xb6, 0x1b, 0x9d, 0x0b, 0x68,
	0xa2, 0x12, 0xcc, 0x7a, 0x8c, 0x8a, 0xe8, 0x97, 0x32, 0x52, 0x14, 0x5c, 0xcd, 0x22, 0xcc, 0x6f,
	0xfe, 0x30, 0x62, 0x44, 0xa3, 0x98, 0x3f, 0xa7, 0xa1, 0xb8, 0x4d, 0x5c, 0xc2, 0x1c, 0x3b, 0x00,
	0x6e, 0x41, 0xe1, 0x68, 0x64, 0xbf, 0x21, 0x7e, 0xb7, 0x87, 0x7d, 0x5c, 0x4a, 0xaf, 0x66, 0xd7,
	0x0a, 0x1b, 0xf7, 0x42, 0x7f, 0x26, 0xb5, 0x2b, 0x75, 0xa9, 0x2a, 0x9c, 0x6c, 0xba, 0x3e, 0x7b,
	0x67, 0xc1, 0x51, 0xf8, 0x50, 0x7e, 0x0c, 0x8b, 0x31, 0x31, 0x32, 0x20, 0xfb, 0x86, 0xbc, 0xd3,
	0x84, 0xc5, 0x11, 0xad, 0xc0, 0xcc, 0x09, 0x1e, 0x8c, 0x88, 0x66, 0xaa, 0x2e, 0xb5, 0xcc, 0x57,
	0x69, 0xf3, 0xa7, 0x0c, 0x2c, 0xee, 0x33, 0x7a, 0xe2, 0xf4, 0x08, 0x0b, 0xc8, 0x55, 0x01, 0x78,
	0xb5, 0x6b, 0xab, 0x9b, 0x84, 0x29, 0x6c, 0xa0, 0x90, 0x5b, 0x18, 0xc7, 0x56, 0xca, 0x9a, 0xe3,
	0x61, 0x50, 0xbf, 0x84, 0x42, 0xdf, 0xe6, 0xa1, 0x55, 0x46, 0x5a, 0x2d, 0x8f, 0x3d, 0x0a, 0x83,
	0xda, 0x4a, 0x59, 0xd0, 0xb7, 0x79, 0x60, 0xf7, 0x08, 0x16, 0xb0, 0x08, 0x56, 0x68, 0x99, 0x95,
	0x96, 0xe3, 0x6f, 0x1b, 0x0d, 0x65, 0x2b, 0x65, 0xcd, 0xe3, 0xc8, 0x1d, 0xd5, 0x61, 0xb1, 0xaf,
	0x62, 0x15, 0xda, 0xe7, 0xa4, 0xfd, 0xf5, 0x53, 0x62, 0xd9, 0x4a, 0x59, 0xc5, 0xfe, 0xc4, 0x4b,
	0x7d, 0x69, 0x2a, 0x02, 0xe6, 0xef, 0x69, 0xc8, 0xab, 0xa8, 0x22, 0x04, 0x39, 0x77, 0x9c, 0x9a,
	0xf2, 0x8c, 0x1a, 0x60, 0x78, 0xda, 0x22, 0xe6, 0x70, 0x29, 0xfc, 0xd9, 0x18, 0xa4, 0xb5, 0xe8,
	0xc5, 0xa2, 0xbc, 0x0a, 0x05, 0xf9, 0xc4, 0x1d, 0xea, 0x12, 0x26, 0xdd, 0x9e, 0xb3, 0xa2, 0x4f,
	0xe8, 0x21, 0x14, 0xb0, 0x6d, 0x13, 0xce, 0xbb, 0x43, 0xda, 0x23, 0xd2, 0xb1, 0x62, 0x24, 0xa4,
	0x9b, 0x52, 0xb6, 0x4b, 0x7b, 0xc4, 0x02, 0x1c, 0x9e, 0xcd, 0x5f, 0x72, 0xb0, 0xdc, 0x60, 0x04,
	0xfb, 0x44, 0x79, 0xa0, 0xeb, 0x0f, 0xdd, 0x09, 0x53, 0x2e, 0xe2, 0x8f, 0xce, 0x24, 0x59, 0x6a,
	0x5f, 0x83, 0xc1, 0x94, 0x6e, 0xd7, 0xd3, 0x85, 0x23, 0xbd, 0x3a, 0xb5, 0xd0, 0x16, 0xb5, 0x7a,
	0xf0, 0x90, 0x18, 0x97, 0xec, 0x65, 0xe3, 0xd2, 0x85, 0xa5, 0x9e, 0xac, 0xff, 0xae, 0x87, 0x19,
	0x1e, 0x12, 0x9f, 0x30, 0x5e, 0xca, 0xc9, 0x02, 0xd9, 0x08, 0x51, 0x12, 0x1c, 0xac, 0xa8, 0xae,
	0xb1, 0x1f, 0x1a, 0xa9, 0x5a, 0x31, 0x7a, 0xb1, 0xe7, 0x78, 0x58, 0x67, 0x2e, 0x14, 0x56, 0xd4,
	0x80, 0x59, 0x4e, 0x6c, 0x46, 0x7c, 0x5e, 0xca, 0x4b, 0x32, 0x9f, 0x9d, 0x49, 0xa6, 0xa3, 0x74,
	0x15, 0x87, 0xc0, 0xb2, 0xdc, 0x80, 0xab, 0x89, 0x2c, 0x2f, 0x53, 0xb2, 0xe5, 0x1a, 0xcc, 0x47,
	0xd1, 0x2f, 0x55, 0xee, 0x4f, 0x61, 0x65, 0x92, 0xad, 0x6e, 0xc3, 0xf7, 0x20, 0xaf, 0x32, 0x41,
	0x97, 0xfb, 0x62, 0xe8, 0x9c, 0x56, 0xd4, 0x62, 0xf3, 0xaf, 0x2c, 0x2c, 0x6f, 0x91, 0x01, 0xf9,
	0x4f, 0x67, 0x57, 0x82, 0x83, 0x17, 0xce, 0xae, 0x48, 0x9e, 0xcc, 0xc4, 0xf2, 0x24, 0x09, 0xf6,
	0x13, 0xcd, 0x93, 0x6b, 0xb0, 0x32, 0xc9, 0x56, 0xe5, 0x89, 0x79, 0x00, 0x0b, 0x9d, 0x6a, 0x83,
	0x91, 0x1e, 0x71, 0x7d, 0x07, 0x0f, 0x38, 0x2a, 0x42, 0xc6, 0xe9, 0x69, 0xcc, 0x8c, 0xd3, 0x13,
	0xf3, 0xdc, 0x23, 0x6c, 0xe8, 0x70, 0xd1, 0xc3, 0x34, 0x6e, 0xe4, 0x45, 0xfc, 0x24, 0x7d, 0x3b,
	0xee, 0x77, 0xea, 0x62, 0xba, 0x50, 0x14, 0x03, 0x22, 0x82, 0x7b, 0x0d, 0xf2, 0xe2, 0xe8, 0x07,
	0x7c, 0xf5, 0x4d, 0xb4, 0x63, 0x46, 0x07, 0x01, 0x63, 0x79, 0x16, 0xba, 0x3d, 0x3a, 0xc4, 0x8e,
	0xab, 0x41, 0xf5, 0x2d, 0x3a, 0xa1, 0x73, 0x93, 0x13, 0xba, 0x0e, 0x86, 0x1a, 0x2b, 0x1f, 0xee,
	0x89, 0xf9, 0x3e, 0x0d, 0x28, 0x98, 0x2d, 0x11, 0x98, 0x3d, 0x28, 0xd8, 0xe3, 0xab, 0x9e, 0xec,
	0x9f, 0x4f, 0x4d, 0xa3, 0xb1, 0x4a, 0x25, 0x72, 0x56, 0x69, 0x10, 0x05, 0x28, 0x3f, 0x01, 0x23,
	0xae, 0x70, 0xa9, 0x2f, 0xf9, 0x47, 0x06, 0x96, 0xc3, 0xaa, 0x88, 0xf0, 0x7c, 0x0a, 0x45, 0x31,
	0xe4, 0x27, 0xa8, 0x8a, 0x5a, 0xba, 0x16, 0x1d, 0xf4, 0x63, 0x69, 0x2b, 0x65, 0x2d, 0xf0, 0x89,
	0x2f, 0x2f, 0x46, 0xaf, 0x18, 0xf8, 0x11, 0x84, 0x4c, 0x7c, 0xf4, 0x4e, 0x7c, 0x53, 0x39, 0x7a,
	0x6d, 0x1e, 0xc5, 0x68, 0xc1, 0x92, 0x1e, 0xfe, 0x11, 0x14, 0x55, 0xd3, 0x37, 0x62, 0x0b, 0xc0,
	0x04, 0x8e, 0x81, 0xe3, 0x5f, 0x6f, 0x0f, 0x96, 0xc3, 0x45, 0x20, 0x82, 0xa5, 0x96, 0x81, 0xff,
	0x9d, 0x11, 0xfe, 0x56, 0xca, 0x42, 0xfd, 0xa9, 0xd7, 0xfa, 0xd5, 0xc4, 0xa8, 0x99, 0x7f, 0x66,
	0xa1, 0xb4, 0xcd, 0xb0, 0xeb, 0xab, 0xba, 0x50, 0xb3, 0xe2, 0x23, 0xf6, 0xc0, 0x17, 0x50, 0x18,
	0xa7, 0xa0, 0x08, 0xd5, 0x64, 0xe3, 0x3a, 0x8d, 0x5a, 0x65, 0x7f, 0x6c, 0xa4, 0x73, 0x2c, 0x02,
	0x93, 0xd8, 0x59, 0x73, 0x97, 0xed, 0xac, 0xad, 0x78, 0xe3, 0xab, 0x9c, 0x4f, 0x2b, 0xb9, 0xfb,
	0x3d, 0x01, 0x23, 0xce, 0xf7, 0xa3, 0x35, 0xbe, 0x36, 0xdc, 0x48, 0x60, 0xab, 0xa7, 0xe4, 0x06,
	0xcc, 0x88, 0xe4, 0x0a, 0xaa, 0xfa, 0xe6, 0x74, 0x70, 0xc6, 0xa9, 0x62, 0x29, 0x55, 0xf3, 0xb7,
	0x1c, 0xdc, 0xb0, 0xc8, 0x09, 0x7d, 0x43, 0xfe, 0xa5, 0x94, 0x69, 0xc2, 0x22, 0x27, 0xec, 0xc4,
	0xb1, 0x49, 0x17, 0xdb, 0x36, 0x1d, 0xb9, 0xc1, 0xd4, 0x3c, 0x9b, 0x7e, 0x51, 0x1b, 0x6d, 0x2a,
	0x1b, 0x74, 0x30, 0x99, 0x79, 0x6a, 0x64, 0x56, 0x43, 0x88, 0x53, 0x5d, 0xfc, 0x80, 0xd4, 0x9b,
	0xb9, 0x6c, 0xea, 0xed, 0xc4, 0x77, 0xb3, 0xf5, 0x0b, 0xf0, 0xfa, 0xf4, 0x72, 0x6f, 0x1f, 0xca,
	0x49, 0x74, 0x3f, 0x3c, 0xf9, 0xee, 0xef, 0xc0, 0x7c, 0x34, 0x39, 0x50, 0x09, 0x56, 0xf6, 0xad,
	0xf6, 0x8b, 0x76, 0xa3, 0xfd, 0xbc, 0x7b, 0xb0, 0xd7, 0xd9, 0x6f, 0x36, 0x76, 0x9e, 0xed, 0x34,
	0xb7, 0x8c, 0x14, 0x2a, 0x02, 0x6c, 0xbe, 0x3a, 0xb0, 0x9a, 0xdd, 0xfa, 0xf3, 0x76, 0xdd, 0x48,
	0xa3, 0x59, 0xc8, 0x6e, 0x37, 0x3a, 0x46, 0x06, 0xe5, 0x21, 0xd3, 0xa9, 0x1a, 0xd9, 0xfb, 0x35,
	0x80, 0xf1, 0x66, 0x8c, 0x56, 0xc0, 0xd8, 0x6d, 0x6f, 0x35, 0x63, 0x20, 0x79, 0xc8, 0x58, 0x6d,
	0x23, 0x2d, 0xfe, 0xbe, 0x6c, 0x2b, 0x5b, 0xeb, 0xa5, 0x91, 0xbd, 0xff, 0x18, 0x50, 0xa7, 0xda,
	0x71, 0xfa, 0x2e, 0xf6, 0x47, 0x8c, 0x1c, 0x12, 0x26, 0x57, 0x81, 0xeb, 0xb0, 0x7c, 0xd8, 0xb4,
	0x3a, 0x3b, 0xed, 0xbd, 0x69, 0x98, 0xc3, 0x0d, 0x05, 0x73, 0xf8, 0xd0, 0xc8, 0x6c, 0xfc, 0x9d,
	0x81, 0x62, 0x83, 0x72, 0x47, 0x7c, 0x6e, 0x46, 0x07, 0x03, 0xc2, 0xd0, 0x2e, 0xcc, 0x47, 0xf7,
	0x58, 0x74, 0xf3, 0xac, 0x65, 0xbc, 0x7c, 0xeb, 0x14, 0xa9, 0x5e, 0x6a, 0x52, 0x02, 0x2e, 0xba,
	0xee, 0x44, 0xe0, 0x12, 0x76, 0xb6, 0x08, 0x5c, 0xe2, 0x8e, 0x94, 0x42, 0xaf, 0x60, 0x69, 0xaa,
	0x89, 0xa0, 0xbb, 0xe7, 0xb6, 0xc3, 0xb2, 0x79, 0x96, 0x8a, 0x4e, 0x83, 0x6f, 0x00, 0x4d, 0x27,
	0x09, 0x32, 0xcf, 0x4f, 0xf8, 0xf2, 0xff, 0xcf, 0xd4, 0x51, 0xf0, 0xb5, 0x47, 0x00, 0x78, 0xe0,
	0xbd, 0xc6, 0x5d, 0xe2, 0x8e, 0x86, 0xe8, 0x66, 0x45, 0xfd, 0xa7, 0xa7, 0x12, 0xfc, 0xa7, 0xa7,
	0xd2, 0x74, 0x47, 0xc3, 0xb6, 0xe7, 0xcb, 0x1e, 0xf0, 0xfe, 0xca, 0x6a, 0x7a, 0xed, 0x8a, 0x35,
	0x27, 0x0d, 0x84, 0xa0, 0xf6, 0x1c, 0x8c, 0xb1, 0x75, 0x57, 0x66, 0x36, 0xba, 0x9b, 0x88, 0x71,
	0x28, 0x64, 0x31, 0xa0, 0x62, 0x08, 0x24, 0xa5, 0xb5, 0xa7, 0x50, 0x10, 0x8c, 0xbb, 0xaa, 0x36,
	0xd1, 0xad, 0x29, 0xa0, 0x67, 0x0e, 0x19, 0xf4, 0x02, 0x90, 0x5f, 0x15, 0x08, 0x08, 0x13, 0x55,
	0x82, 0x02, 0x40, 0xd1, 0x39, 0x16, 0x8a, 0xe7, 0x01, 0x68, 0x16, 0xca, 0x7f, 0x29, 0xa9, 0x35,
	0x61, 0x41, 0x01, 0x0c, 0x09, 0xe7, 0xb8, 0x4f, 0xd0, 0x9d, 0x29, 0x88, 0x5d, 0x25, 0x89, 0x81,
	0xcc, 0x4b, 0x33, 0x2d, 0xab, 0xd5, 0x61, 0x3e, 0x80, 0xf1, 0x5f, 0xd3, 0x1e, 0xba, 0x9d, 0x80,
	0x22, 0x04, 0x31, 0x90, 0x82, 0x06, 0x11, 0xa2, 0x31, 0x15, 0xdd, 0x97, 0x13, 0xa8, 0x74, 0x94,
	0x24, 0x91, 0x8a, 0x96, 0xd5, 0xf3, 0xaf, 0x72, 0x22, 0x40, 0x47, 0x79, 0x69, 0x55, 0xfd, 0x27,
	0x00, 0x00, 0xff, 0xff, 0xa7, 0x47, 0xa2, 0x0f, 0x56, 0x14, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CosiControllerClient is the client API for CosiController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CosiControllerClient interface {
	CreateBucket(ctx context.Context, in *CreateBucketRequest, opts ...grpc.CallOption) (*CreateBucketResponse, error)
	DeleteBucket(ctx context.Context, in *DeleteBucketRequest, opts ...grpc.CallOption) (*DeleteBucketResponse, error)
	GrantBucketAccess(ctx context.Context, in *GrantBucketAccessRequest, opts ...grpc.CallOption) (*GrantBucketAccessResponse, error)
	RevokeBucketAccess(ctx context.Context, in *RevokeBucketAccessRequest, opts ...grpc.CallOption) (*RevokeBucketAccessResponse, error)
}

type cosiControllerClient struct {
	cc *grpc.ClientConn
}

func NewCosiControllerClient(cc *grpc.ClientConn) CosiControllerClient {
	return &cosiControllerClient{cc}
}

func (c *cosiControllerClient) CreateBucket(ctx context.Context, in *CreateBucketRequest, opts ...grpc.CallOption) (*CreateBucketResponse, error) {
	out := new(CreateBucketResponse)
	err := c.cc.Invoke(ctx, "/cosi.v1.CosiController/CreateBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cosiControllerClient) DeleteBucket(ctx context.Context, in *DeleteBucketRequest, opts ...grpc.CallOption) (*DeleteBucketResponse, error) {
	out := new(DeleteBucketResponse)
	err := c.cc.Invoke(ctx, "/cosi.v1.CosiController/DeleteBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cosiControllerClient) GrantBucketAccess(ctx context.Context, in *GrantBucketAccessRequest, opts ...grpc.CallOption) (*GrantBucketAccessResponse, error) {
	out := new(GrantBucketAccessResponse)
	err := c.cc.Invoke(ctx, "/cosi.v1.CosiController/GrantBucketAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cosiControllerClient) RevokeBucketAccess(ctx context.Context, in *RevokeBucketAccessRequest, opts ...grpc.CallOption) (*RevokeBucketAccessResponse, error) {
	out := new(RevokeBucketAccessResponse)
	err := c.cc.Invoke(ctx, "/cosi.v1.CosiController/RevokeBucketAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CosiControllerServer is the server API for CosiController service.
type CosiControllerServer interface {
	CreateBucket(context.Context, *CreateBucketRequest) (*CreateBucketResponse, error)
	DeleteBucket(context.Context, *DeleteBucketRequest) (*DeleteBucketResponse, error)
	GrantBucketAccess(context.Context, *GrantBucketAccessRequest) (*GrantBucketAccessResponse, error)
	RevokeBucketAccess(context.Context, *RevokeBucketAccessRequest) (*RevokeBucketAccessResponse, error)
}

// UnimplementedCosiControllerServer can be embedded to have forward compatible implementations.
type UnimplementedCosiControllerServer struct {
}

func (*UnimplementedCosiControllerServer) CreateBucket(ctx context.Context, req *CreateBucketRequest) (*CreateBucketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBucket not implemented")
}
func (*UnimplementedCosiControllerServer) DeleteBucket(ctx context.Context, req *DeleteBucketRequest) (*DeleteBucketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBucket not implemented")
}
func (*UnimplementedCosiControllerServer) GrantBucketAccess(ctx context.Context, req *GrantBucketAccessRequest) (*GrantBucketAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantBucketAccess not implemented")
}
func (*UnimplementedCosiControllerServer) RevokeBucketAccess(ctx context.Context, req *RevokeBucketAccessRequest) (*RevokeBucketAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeBucketAccess not implemented")
}

func RegisterCosiControllerServer(s *grpc.Server, srv CosiControllerServer) {
	s.RegisterService(&_CosiController_serviceDesc, srv)
}

func _CosiController_CreateBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CosiControllerServer).CreateBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosi.v1.CosiController/CreateBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CosiControllerServer).CreateBucket(ctx, req.(*CreateBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CosiController_DeleteBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CosiControllerServer).DeleteBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosi.v1.CosiController/DeleteBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CosiControllerServer).DeleteBucket(ctx, req.(*DeleteBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CosiController_GrantBucketAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantBucketAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CosiControllerServer).GrantBucketAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosi.v1.CosiController/GrantBucketAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CosiControllerServer).GrantBucketAccess(ctx, req.(*GrantBucketAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CosiController_RevokeBucketAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeBucketAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CosiControllerServer).RevokeBucketAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosi.v1.CosiController/RevokeBucketAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CosiControllerServer).RevokeBucketAccess(ctx, req.(*RevokeBucketAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CosiController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosi.v1.CosiController",
	HandlerType: (*CosiControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBucket",
			Handler:    _CosiController_CreateBucket_Handler,
		},
		{
			MethodName: "DeleteBucket",
			Handler:    _CosiController_DeleteBucket_Handler,
		},
		{
			MethodName: "GrantBucketAccess",
			Handler:    _CosiController_GrantBucketAccess_Handler,
		},
		{
			MethodName: "RevokeBucketAccess",
			Handler:    _CosiController_RevokeBucketAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/container-object-storage-interface/spec/cosi.proto",
}
